[package]
name = "quickgui-docs-demo"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-time = "1.1"
quickgui = { path = "../..", default-features = false, features = ["markdown"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.128"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["HtmlCanvasElement"] }

[dev-dependencies]
quickgui = { path = "../..", default-features = false, features = ["markdown", "test-support"] }
