[package]
name = "quickgui-editor"
version = "0.1.6"
edition = "2024"
rust-version = "1.90"
description = "Editor, CodeBlock and DiffView native component extension"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["editor", "language-packs"]
editor = []
language-packs = ["tree-sitter/wasm", "dep:tar", "dep:sha2"]
bundled-languages = ["dep:tree-sitter-bash", "dep:tree-sitter-cpp", "dep:tree-sitter-css", "dep:tree-sitter-go", "dep:tree-sitter-html", "dep:tree-sitter-java", "dep:tree-sitter-javascript", "dep:tree-sitter-json", "dep:tree-sitter-markdown", "dep:tree-sitter-python", "dep:tree-sitter-ruby", "dep:tree-sitter-rust", "dep:tree-sitter-sequel", "dep:tree-sitter-swift", "dep:tree-sitter-toml-ng", "dep:tree-sitter-typescript", "dep:tree-sitter-yaml"]

[dependencies]
quickgui-extension-sdk = { path = "../../crates/quickgui-extension-sdk", version = "=0.1.6" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tar = { version = "0.4", default-features = false, optional = true }
sha2 = { version = "0.10", optional = true }
tree-sitter = "=0.26.7"
imara-diff = { version = "0.2.0" }
tree-sitter-bash = { version = "0.25.1", optional = true }
tree-sitter-cpp = { version = "0.23.4", optional = true }
tree-sitter-css = { version = "0.25.0", optional = true }
tree-sitter-go = { version = "0.25.0", optional = true }
tree-sitter-highlight = { version = "=0.26.7" }
tree-sitter-html = { version = "0.23.2", optional = true }
tree-sitter-java = { version = "0.23.5", optional = true }
tree-sitter-javascript = { version = "0.25.0", optional = true }
tree-sitter-json = { version = "0.24.8", optional = true }
tree-sitter-markdown = { package = "tree-sitter-md-025", version = "0.5.6", optional = true }
tree-sitter-python = { version = "0.25.0", optional = true }
tree-sitter-ruby = { version = "0.23.1", optional = true }
tree-sitter-rust = { version = "0.24.2", optional = true }
tree-sitter-sequel = { version = "0.3.11", optional = true }
tree-sitter-swift = { version = "0.7.3", optional = true }
tree-sitter-toml-ng = { version = "0.7.0", optional = true }
tree-sitter-typescript = { version = "0.23.2", optional = true }
tree-sitter-yaml = { version = "0.7.2", optional = true }

[dev-dependencies]
tree-sitter-lua = "0.5.0"
quickgui = { path = "../..", default-features = false, features = ["test-support", "text-input-decorations"] }
