/**
 * Windows installer generation.
 *
 * QuickGUI writes an NSIS script and runs `makensis` when it is on PATH. Authenticode signing is a
 * separate, explicitly configured step that only runs when the build host is Windows, because
 * `signtool.exe` has no cross-platform equivalent.
 */

import { existsSync, statSync } from "node:fs";

import { CliError } from "../error.ts";
import {
  nsisFileAssociationCommands,
  nsisFileAssociationRemovalCommands,
  nsisProtocolCommands,
  nsisString,
  type ResolvedDocumentType,
} from "./documents.ts";

/** Default RFC 3161 timestamp service used when the configuration does not name one. */
export const DEFAULT_TIMESTAMP_URL = "http://timestamp.digicert.com";

function extraFileIsDirectory(source: string): boolean {
  try {
    return existsSync(source) && statSync(source).isDirectory();
  } catch {
    return false;
  }
}

function extraFileInstall(source: string, name: string): string {
  if (extraFileIsDirectory(source)) {
    return [
      `  CreateDirectory "$INSTDIR\\${nsisString(name)}"`,
      `  SetOutPath "$INSTDIR\\${nsisString(name)}"`,
      `  File /r "${nsisString(source)}\\*.*"`,
      `  SetOutPath "$INSTDIR"`,
    ].join("\n");
  }
  return `  File "/oname=${nsisString(name)}" "${nsisString(source)}"`;
}

function extraFileRemoval(source: string, name: string): string {
  if (extraFileIsDirectory(source)) {
    return `  RMDir /r "$INSTDIR\\${nsisString(name)}"`;
  }
  return `  Delete "$INSTDIR\\${nsisString(name)}"`;
}

export interface NsisScriptOptions {
  name: string;
  executableName: string;
  identifier: string;
  version: string;
  publisher: string;
  /** Path of the compiled executable, relative to the script or absolute. */
  executablePath: string;
  /** Additional payload files copied next to the executable, as `[sourcePath, installedName]`. */
  extraFiles?: ReadonlyArray<readonly [string, string]>;
  outputFile: string;
  iconPath?: string;
  installDirectory?: string;
  perMachine?: boolean;
  createDesktopShortcut?: boolean;
  createStartMenuShortcut?: boolean;
  protocols: readonly string[];
  documentTypes: readonly ResolvedDocumentType[];
}

/** Generate a self-contained NSIS script. No NSIS plugins beyond the bundled ones are required. */
export function nsisScript(options: NsisScriptOptions): string {
  // `installDirectory` is an NSIS expression: `$LOCALAPPDATA` and friends must survive verbatim,
  // so only the application name interpolated into the default is escaped.
  const installDirectory =
    options.installDirectory ??
    `${options.perMachine ? "$PROGRAMFILES64" : "$LOCALAPPDATA"}\\${nsisString(options.name)}`;
  const uninstallKey = `Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${options.identifier}`;
  const associations = nsisFileAssociationCommands(
    options.identifier,
    options.executableName,
    options.documentTypes,
  );
  const protocols = nsisProtocolCommands(options.executableName, options.protocols);
  const removals = [
    ...nsisFileAssociationRemovalCommands(options.identifier, options.documentTypes),
    ...options.protocols.map((protocol) => `DeleteRegKey SHCTX "Software\\Classes\\${protocol}"`),
  ];
  const extraFiles = (options.extraFiles ?? []).map(([source, name]) => extraFileInstall(source, name));
  const extraRemovals = (options.extraFiles ?? []).map(([source, name]) => extraFileRemoval(source, name));

  return `; Generated by @quickgui/cli. Edit your QuickGUI config instead of this file.
Unicode true
ManifestDPIAware true
SetCompressor /SOLID lzma

!include "MUI2.nsh"
!include "FileFunc.nsh"

Name "${nsisString(options.name)}"
OutFile "${nsisString(options.outputFile)}"
InstallDir "${installDirectory}"
InstallDirRegKey SHCTX "${nsisString(uninstallKey)}" "InstallLocation"
RequestExecutionLevel ${options.perMachine ? "admin" : "user"}
VIProductVersion "${windowsFileVersion(options.version)}"
VIAddVersionKey "ProductName" "${nsisString(options.name)}"
VIAddVersionKey "CompanyName" "${nsisString(options.publisher)}"
VIAddVersionKey "FileVersion" "${nsisString(options.version)}"
VIAddVersionKey "ProductVersion" "${nsisString(options.version)}"
VIAddVersionKey "LegalCopyright" "${nsisString(options.publisher)}"
VIAddVersionKey "FileDescription" "${nsisString(options.name)} installer"
${options.iconPath ? `!define MUI_ICON "${nsisString(options.iconPath)}"\n!define MUI_UNICON "${nsisString(options.iconPath)}"` : ""}

!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Function .onInit
  SetShellVarContext ${options.perMachine ? "all" : "current"}
FunctionEnd

Function un.onInit
  SetShellVarContext ${options.perMachine ? "all" : "current"}
FunctionEnd

Section "Install"
  SetOutPath "$INSTDIR"
  File "/oname=${nsisString(options.executableName)}" "${nsisString(options.executablePath)}"
${extraFiles.join("\n")}
  WriteUninstaller "$INSTDIR\\Uninstall.exe"

  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "DisplayName" "${nsisString(options.name)}"
  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "DisplayVersion" "${nsisString(options.version)}"
  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "Publisher" "${nsisString(options.publisher)}"
  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "DisplayIcon" "$INSTDIR\\${nsisString(options.executableName)}"
  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "InstallLocation" "$INSTDIR"
  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'
  WriteRegStr SHCTX "${nsisString(uninstallKey)}" "QuietUninstallString" '"$INSTDIR\\Uninstall.exe" /S'
  WriteRegDWORD SHCTX "${nsisString(uninstallKey)}" "NoModify" 1
  WriteRegDWORD SHCTX "${nsisString(uninstallKey)}" "NoRepair" 1
  \${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  WriteRegDWORD SHCTX "${nsisString(uninstallKey)}" "EstimatedSize" "$0"

${indent(protocols)}
${indent(associations)}

${
  options.createStartMenuShortcut === false
    ? ""
    : `  CreateDirectory "$SMPROGRAMS\\${nsisString(options.name)}"
  CreateShortCut "$SMPROGRAMS\\${nsisString(options.name)}\\${nsisString(options.name)}.lnk" "$INSTDIR\\${nsisString(options.executableName)}"`
}
${
  options.createDesktopShortcut === false
    ? ""
    : `  CreateShortCut "$DESKTOP\\${nsisString(options.name)}.lnk" "$INSTDIR\\${nsisString(options.executableName)}"`
}
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, i 0, i 0)'
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\\${nsisString(options.executableName)}"
${extraRemovals.join("\n")}
  Delete "$INSTDIR\\Uninstall.exe"
  RMDir "$INSTDIR"
  Delete "$SMPROGRAMS\\${nsisString(options.name)}\\${nsisString(options.name)}.lnk"
  RMDir "$SMPROGRAMS\\${nsisString(options.name)}"
  Delete "$DESKTOP\\${nsisString(options.name)}.lnk"
${indent(removals)}
  DeleteRegKey SHCTX "${nsisString(uninstallKey)}"
  System::Call 'shell32::SHChangeNotify(i 0x08000000, i 0, i 0, i 0)'
SectionEnd
`;
}

function indent(commands: readonly string[]): string {
  return commands.map((command) => `  ${command}`).join("\n");
}

/** NSIS `VIProductVersion` needs exactly four numeric components. */
export function windowsFileVersion(version: string): string {
  const parts = version
    .split(/[.+-]/)
    .slice(0, 4)
    .map((part) => (/^\d+$/.test(part) ? Math.min(65_535, Number(part)) : 0));
  while (parts.length < 4) parts.push(0);
  return parts.join(".");
}

export function makensisArguments(scriptPath: string): string[] {
  return ["makensis", "-V2", scriptPath];
}

export interface SignToolInput {
  artifact: string;
  certificateFile?: string;
  subjectName?: string;
  password?: string;
  timestampUrl?: string;
  digest?: "sha256" | "sha384" | "sha512";
}

/** `signtool sign` command line. Exactly one of a certificate file or a subject name is required. */
export function signToolArguments(input: SignToolInput): string[] {
  if ((input.certificateFile === undefined) === (input.subjectName === undefined)) {
    throw new CliError(
      "Windows signing needs exactly one of `windows.signing.certificateFile` or `windows.signing.subjectName`",
    );
  }
  return [
    "signtool",
    "sign",
    "/fd",
    input.digest ?? "sha256",
    "/td",
    input.digest ?? "sha256",
    "/tr",
    input.timestampUrl ?? DEFAULT_TIMESTAMP_URL,
    ...(input.certificateFile ? ["/f", input.certificateFile] : []),
    ...(input.subjectName ? ["/n", input.subjectName] : []),
    ...(input.password ? ["/p", input.password] : []),
    input.artifact,
  ];
}
