import { buildDemoSources } from "./build-demo-sources";
import { ensureWasmBindgen } from "./wasm-bindgen";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile, cp, rm, readdir } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "../..");
async function writeChanged(path: string, content: string) {
  if (!(await Bun.file(path).exists()) || (await readFile(path, "utf8")) !== content) {
    await writeFile(path, content);
  }
}
async function run(args: string[], env: Record<string, string | undefined> = {}) {
  const child = Bun.spawn(args, {
    cwd: root,
    env: { ...process.env, ...env },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (await child.exited) throw new Error(`Command failed: ${args.join(" ")}`);
}

function macosRustToolEnvironment(): Record<string, string | undefined> {
  if (process.platform !== "darwin") return {};
  const result = Bun.spawnSync(["rustc", "--print", "sysroot"], {
    cwd: root,
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) {
    throw new Error(`Could not locate the Rust sysroot: ${result.stderr.toString().trim()}`);
  }
  const llvmDirectory = resolve(result.stdout.toString().trim(), "lib");
  return {
    // Compiler cache wrappers may discard the dynamic-library path before rustc launches the
    // toolchain's dynamically linked rust-lld. Keep this size-optimized WASM link deterministic.
    CARGO_BUILD_RUSTC_WRAPPER: "",
    RUSTC_WRAPPER: "",
    DYLD_LIBRARY_PATH: [llvmDirectory, process.env.DYLD_LIBRARY_PATH]
      .filter((entry): entry is string => Boolean(entry))
      .join(":"),
  };
}
const source = await readFile(resolve(root, "crates/quickgui-docs-demo/src/lib.rs"), "utf8");
const ids = [
  ...source.match(/pub const COMPONENTS:[\s\S]*?= &\[([\s\S]*?)\];/)![1].matchAll(/"([a-z-]+)"/g),
].map((match) => match[1]);
await writeChanged(
  resolve(root, "website/src/lib/component-demos.ts"),
  `// Generated by scripts/build-demos.ts.\nexport const DEMO_COMPONENTS: readonly string[] = ${JSON.stringify(ids)}\n`,
);
if (process.argv.includes("--catalog-only")) process.exit(0);
const wasmBindgen = await ensureWasmBindgen(root);
await run(
  [
    "cargo",
    "build",
    "--locked",
    "-p",
    "quickgui-docs-demo",
    "--target",
    "wasm32-unknown-unknown",
    "--profile",
    "docs-wasm",
  ],
  macosRustToolEnvironment(),
);
const wasm = resolve(root, "target/wasm32-unknown-unknown/docs-wasm/quickgui_docs_demo.wasm");
const hash = createHash("sha256")
  .update(await readFile(wasm))
  .digest("hex")
  .slice(0, 12);
const destination = resolve(root, "website/public/demos");
const stage = resolve(root, "target/docs-demo-web", hash);
await mkdir(stage, { recursive: true });
await run([wasmBindgen, "--target", "web", "--out-name", "quickgui", "--out-dir", stage, wasm]);
await buildDemoSources();
await mkdir(destination, { recursive: true });
if (
  !(await Bun.file(resolve(destination, hash, "quickgui.js")).exists()) ||
  !(await Bun.file(resolve(destination, hash, "quickgui_bg.wasm")).exists())
) {
  await cp(stage, resolve(destination, hash), { recursive: true });
}
await writeChanged(
  resolve(destination, hash, "Inter-LICENSE.txt"),
  await readFile(resolve(root, "tests/fixtures/fonts/Inter-LICENSE"), "utf8"),
);
const template = await readFile(resolve(root, "website/demos/index.html"), "utf8");
await writeChanged(resolve(destination, "index.html"), template.replaceAll("__DEMO_BUILD__", hash));
await writeChanged(
  resolve(destination, "manifest.json"),
  JSON.stringify({ hash, components: ids }) + "\n",
);
// Only publish the current content-addressed bundle after its wrapper is ready.
for (const entry of await readdir(destination, { withFileTypes: true })) {
  if (entry.isDirectory() && /^[a-f0-9]{12}$/.test(entry.name) && entry.name !== hash) {
    await rm(resolve(destination, entry.name), { recursive: true });
  }
}
console.log(`Built ${ids.length} Rust component demos → public/demos/${hash}`);
