// Code generated by bun scripts/generate-style-helpers.ts; DO NOT EDIT.

/** Fixed Rust style presets for typed style objects. */
export interface StyleHelpers {
  /** Matches Rust's absolute. */
  absolute?: boolean | null | undefined;
  /** Matches Rust's app_region_drag. */
  appRegionDrag?: boolean | null | undefined;
  /** Matches Rust's app_region_no_drag. */
  appRegionNoDrag?: boolean | null | undefined;
  /** Matches Rust's aspect_square. */
  aspectSquare?: boolean | null | undefined;
  /** Matches Rust's block. */
  block?: boolean | null | undefined;
  /** Matches Rust's border_dashed. */
  borderDashed?: boolean | null | undefined;
  /** Matches Rust's border_dotted. */
  borderDotted?: boolean | null | undefined;
  /** Matches Rust's border_solid. */
  borderSolid?: boolean | null | undefined;
  /** Matches Rust's col_end_auto. */
  colEndAuto?: boolean | null | undefined;
  /** Matches Rust's col_span_full. */
  colSpanFull?: boolean | null | undefined;
  /** Matches Rust's col_start_auto. */
  colStartAuto?: boolean | null | undefined;
  /** Matches Rust's content_around. */
  contentAround?: boolean | null | undefined;
  /** Matches Rust's content_between. */
  contentBetween?: boolean | null | undefined;
  /** Matches Rust's content_center. */
  contentCenter?: boolean | null | undefined;
  /** Matches Rust's content_end. */
  contentEnd?: boolean | null | undefined;
  /** Matches Rust's content_evenly. */
  contentEvenly?: boolean | null | undefined;
  /** Matches Rust's content_normal. */
  contentNormal?: boolean | null | undefined;
  /** Matches Rust's content_start. */
  contentStart?: boolean | null | undefined;
  /** Matches Rust's content_stretch. */
  contentStretch?: boolean | null | undefined;
  /** Matches Rust's cursor_alias. */
  cursorAlias?: boolean | null | undefined;
  /** Matches Rust's cursor_col_resize. */
  cursorColResize?: boolean | null | undefined;
  /** Matches Rust's cursor_context_menu. */
  cursorContextMenu?: boolean | null | undefined;
  /** Matches Rust's cursor_copy. */
  cursorCopy?: boolean | null | undefined;
  /** Matches Rust's cursor_crosshair. */
  cursorCrosshair?: boolean | null | undefined;
  /** Matches Rust's cursor_default. */
  cursorDefault?: boolean | null | undefined;
  /** Matches Rust's cursor_e_resize. */
  cursorEResize?: boolean | null | undefined;
  /** Matches Rust's cursor_ew_resize. */
  cursorEwResize?: boolean | null | undefined;
  /** Matches Rust's cursor_grab. */
  cursorGrab?: boolean | null | undefined;
  /** Matches Rust's cursor_grabbing. */
  cursorGrabbing?: boolean | null | undefined;
  /** Matches Rust's cursor_move. */
  cursorMove?: boolean | null | undefined;
  /** Matches Rust's cursor_n_resize. */
  cursorNResize?: boolean | null | undefined;
  /** Matches Rust's cursor_nesw_resize. */
  cursorNeswResize?: boolean | null | undefined;
  /** Matches Rust's cursor_no_drop. */
  cursorNoDrop?: boolean | null | undefined;
  /** Matches Rust's cursor_not_allowed. */
  cursorNotAllowed?: boolean | null | undefined;
  /** Matches Rust's cursor_ns_resize. */
  cursorNsResize?: boolean | null | undefined;
  /** Matches Rust's cursor_nwse_resize. */
  cursorNwseResize?: boolean | null | undefined;
  /** Matches Rust's cursor_pointer. */
  cursorPointer?: boolean | null | undefined;
  /** Matches Rust's cursor_row_resize. */
  cursorRowResize?: boolean | null | undefined;
  /** Matches Rust's cursor_s_resize. */
  cursorSResize?: boolean | null | undefined;
  /** Matches Rust's cursor_text. */
  cursorText?: boolean | null | undefined;
  /** Matches Rust's cursor_vertical_text. */
  cursorVerticalText?: boolean | null | undefined;
  /** Matches Rust's cursor_w_resize. */
  cursorWResize?: boolean | null | undefined;
  /** Matches Rust's flex. */
  flex?: boolean | null | undefined;
  /** Matches Rust's flex_1. */
  flex1?: boolean | null | undefined;
  /** Matches Rust's flex_auto. */
  flexAuto?: boolean | null | undefined;
  /** Matches Rust's flex_basis_auto. */
  flexBasisAuto?: boolean | null | undefined;
  /** Matches Rust's flex_col. */
  flexCol?: boolean | null | undefined;
  /** Matches Rust's flex_col_reverse. */
  flexColReverse?: boolean | null | undefined;
  /** Matches Rust's flex_grow_0. */
  flexGrow0?: boolean | null | undefined;
  /** Matches Rust's flex_grow_1. */
  flexGrow1?: boolean | null | undefined;
  /** Matches Rust's flex_initial. */
  flexInitial?: boolean | null | undefined;
  /** Matches Rust's flex_none. */
  flexNone?: boolean | null | undefined;
  /** Matches Rust's flex_nowrap. */
  flexNowrap?: boolean | null | undefined;
  /** Matches Rust's flex_row. */
  flexRow?: boolean | null | undefined;
  /** Matches Rust's flex_row_reverse. */
  flexRowReverse?: boolean | null | undefined;
  /** Matches Rust's flex_shrink_0. */
  flexShrink0?: boolean | null | undefined;
  /** Matches Rust's flex_shrink_1. */
  flexShrink1?: boolean | null | undefined;
  /** Matches Rust's flex_wrap. */
  flexWrap?: boolean | null | undefined;
  /** Matches Rust's flex_wrap_reverse. */
  flexWrapReverse?: boolean | null | undefined;
  /** Matches Rust's font_bold. */
  fontBold?: boolean | null | undefined;
  /** Matches Rust's font_medium. */
  fontMedium?: boolean | null | undefined;
  /** Matches Rust's font_normal. */
  fontNormal?: boolean | null | undefined;
  /** Matches Rust's font_semibold. */
  fontSemibold?: boolean | null | undefined;
  /** Matches Rust's gap_1. */
  gap1?: boolean | null | undefined;
  /** Matches Rust's gap_2. */
  gap2?: boolean | null | undefined;
  /** Matches Rust's gap_3. */
  gap3?: boolean | null | undefined;
  /** Matches Rust's gap_4. */
  gap4?: boolean | null | undefined;
  /** Matches Rust's gap_5. */
  gap5?: boolean | null | undefined;
  /** Matches Rust's gap_6. */
  gap6?: boolean | null | undefined;
  /** Matches Rust's gap_x_0. */
  gapX0?: boolean | null | undefined;
  /** Matches Rust's gap_x_1. */
  gapX1?: boolean | null | undefined;
  /** Matches Rust's gap_x_2. */
  gapX2?: boolean | null | undefined;
  /** Matches Rust's gap_x_3. */
  gapX3?: boolean | null | undefined;
  /** Matches Rust's gap_x_4. */
  gapX4?: boolean | null | undefined;
  /** Matches Rust's gap_x_5. */
  gapX5?: boolean | null | undefined;
  /** Matches Rust's gap_x_6. */
  gapX6?: boolean | null | undefined;
  /** Matches Rust's gap_y_0. */
  gapY0?: boolean | null | undefined;
  /** Matches Rust's gap_y_1. */
  gapY1?: boolean | null | undefined;
  /** Matches Rust's gap_y_2. */
  gapY2?: boolean | null | undefined;
  /** Matches Rust's gap_y_3. */
  gapY3?: boolean | null | undefined;
  /** Matches Rust's gap_y_4. */
  gapY4?: boolean | null | undefined;
  /** Matches Rust's gap_y_5. */
  gapY5?: boolean | null | undefined;
  /** Matches Rust's gap_y_6. */
  gapY6?: boolean | null | undefined;
  /** Matches Rust's grid. */
  grid?: boolean | null | undefined;
  /** Matches Rust's grid_flow_col. */
  gridFlowCol?: boolean | null | undefined;
  /** Matches Rust's grid_flow_col_dense. */
  gridFlowColDense?: boolean | null | undefined;
  /** Matches Rust's grid_flow_row. */
  gridFlowRow?: boolean | null | undefined;
  /** Matches Rust's grid_flow_row_dense. */
  gridFlowRowDense?: boolean | null | undefined;
  /** Matches Rust's h_10. */
  h10?: boolean | null | undefined;
  /** Matches Rust's h_12. */
  h12?: boolean | null | undefined;
  /** Matches Rust's h_8. */
  h8?: boolean | null | undefined;
  /** Matches Rust's h_full. */
  hFull?: boolean | null | undefined;
  /** Matches Rust's hidden. */
  hidden?: boolean | null | undefined;
  /** Matches Rust's inset_0. */
  inset0?: boolean | null | undefined;
  /** Matches Rust's invisible. */
  invisible?: boolean | null | undefined;
  /** Matches Rust's items_baseline. */
  itemsBaseline?: boolean | null | undefined;
  /** Matches Rust's items_center. */
  itemsCenter?: boolean | null | undefined;
  /** Matches Rust's items_end. */
  itemsEnd?: boolean | null | undefined;
  /** Matches Rust's items_start. */
  itemsStart?: boolean | null | undefined;
  /** Matches Rust's items_stretch. */
  itemsStretch?: boolean | null | undefined;
  /** Matches Rust's justify_around. */
  justifyAround?: boolean | null | undefined;
  /** Matches Rust's justify_between. */
  justifyBetween?: boolean | null | undefined;
  /** Matches Rust's justify_center. */
  justifyCenter?: boolean | null | undefined;
  /** Matches Rust's justify_end. */
  justifyEnd?: boolean | null | undefined;
  /** Matches Rust's justify_evenly. */
  justifyEvenly?: boolean | null | undefined;
  /** Matches Rust's justify_start. */
  justifyStart?: boolean | null | undefined;
  /** Matches Rust's ltr. */
  ltr?: boolean | null | undefined;
  /** Matches Rust's m_0. */
  m0?: boolean | null | undefined;
  /** Matches Rust's m_1. */
  m1?: boolean | null | undefined;
  /** Matches Rust's m_10. */
  m10?: boolean | null | undefined;
  /** Matches Rust's m_12. */
  m12?: boolean | null | undefined;
  /** Matches Rust's m_16. */
  m16?: boolean | null | undefined;
  /** Matches Rust's m_2. */
  m2?: boolean | null | undefined;
  /** Matches Rust's m_20. */
  m20?: boolean | null | undefined;
  /** Matches Rust's m_24. */
  m24?: boolean | null | undefined;
  /** Matches Rust's m_3. */
  m3?: boolean | null | undefined;
  /** Matches Rust's m_32. */
  m32?: boolean | null | undefined;
  /** Matches Rust's m_4. */
  m4?: boolean | null | undefined;
  /** Matches Rust's m_5. */
  m5?: boolean | null | undefined;
  /** Matches Rust's m_6. */
  m6?: boolean | null | undefined;
  /** Matches Rust's m_8. */
  m8?: boolean | null | undefined;
  /** Matches Rust's m_auto. */
  mAuto?: boolean | null | undefined;
  /** Matches Rust's mb_0. */
  mb0?: boolean | null | undefined;
  /** Matches Rust's mb_1. */
  mb1?: boolean | null | undefined;
  /** Matches Rust's mb_10. */
  mb10?: boolean | null | undefined;
  /** Matches Rust's mb_12. */
  mb12?: boolean | null | undefined;
  /** Matches Rust's mb_16. */
  mb16?: boolean | null | undefined;
  /** Matches Rust's mb_2. */
  mb2?: boolean | null | undefined;
  /** Matches Rust's mb_20. */
  mb20?: boolean | null | undefined;
  /** Matches Rust's mb_24. */
  mb24?: boolean | null | undefined;
  /** Matches Rust's mb_3. */
  mb3?: boolean | null | undefined;
  /** Matches Rust's mb_32. */
  mb32?: boolean | null | undefined;
  /** Matches Rust's mb_4. */
  mb4?: boolean | null | undefined;
  /** Matches Rust's mb_5. */
  mb5?: boolean | null | undefined;
  /** Matches Rust's mb_6. */
  mb6?: boolean | null | undefined;
  /** Matches Rust's mb_8. */
  mb8?: boolean | null | undefined;
  /** Matches Rust's mb_auto. */
  mbAuto?: boolean | null | undefined;
  /** Matches Rust's ml_0. */
  ml0?: boolean | null | undefined;
  /** Matches Rust's ml_1. */
  ml1?: boolean | null | undefined;
  /** Matches Rust's ml_10. */
  ml10?: boolean | null | undefined;
  /** Matches Rust's ml_12. */
  ml12?: boolean | null | undefined;
  /** Matches Rust's ml_16. */
  ml16?: boolean | null | undefined;
  /** Matches Rust's ml_2. */
  ml2?: boolean | null | undefined;
  /** Matches Rust's ml_20. */
  ml20?: boolean | null | undefined;
  /** Matches Rust's ml_24. */
  ml24?: boolean | null | undefined;
  /** Matches Rust's ml_3. */
  ml3?: boolean | null | undefined;
  /** Matches Rust's ml_32. */
  ml32?: boolean | null | undefined;
  /** Matches Rust's ml_4. */
  ml4?: boolean | null | undefined;
  /** Matches Rust's ml_5. */
  ml5?: boolean | null | undefined;
  /** Matches Rust's ml_6. */
  ml6?: boolean | null | undefined;
  /** Matches Rust's ml_8. */
  ml8?: boolean | null | undefined;
  /** Matches Rust's ml_auto. */
  mlAuto?: boolean | null | undefined;
  /** Matches Rust's mr_0. */
  mr0?: boolean | null | undefined;
  /** Matches Rust's mr_1. */
  mr1?: boolean | null | undefined;
  /** Matches Rust's mr_10. */
  mr10?: boolean | null | undefined;
  /** Matches Rust's mr_12. */
  mr12?: boolean | null | undefined;
  /** Matches Rust's mr_16. */
  mr16?: boolean | null | undefined;
  /** Matches Rust's mr_2. */
  mr2?: boolean | null | undefined;
  /** Matches Rust's mr_20. */
  mr20?: boolean | null | undefined;
  /** Matches Rust's mr_24. */
  mr24?: boolean | null | undefined;
  /** Matches Rust's mr_3. */
  mr3?: boolean | null | undefined;
  /** Matches Rust's mr_32. */
  mr32?: boolean | null | undefined;
  /** Matches Rust's mr_4. */
  mr4?: boolean | null | undefined;
  /** Matches Rust's mr_5. */
  mr5?: boolean | null | undefined;
  /** Matches Rust's mr_6. */
  mr6?: boolean | null | undefined;
  /** Matches Rust's mr_8. */
  mr8?: boolean | null | undefined;
  /** Matches Rust's mr_auto. */
  mrAuto?: boolean | null | undefined;
  /** Matches Rust's mt_0. */
  mt0?: boolean | null | undefined;
  /** Matches Rust's mt_1. */
  mt1?: boolean | null | undefined;
  /** Matches Rust's mt_10. */
  mt10?: boolean | null | undefined;
  /** Matches Rust's mt_12. */
  mt12?: boolean | null | undefined;
  /** Matches Rust's mt_16. */
  mt16?: boolean | null | undefined;
  /** Matches Rust's mt_2. */
  mt2?: boolean | null | undefined;
  /** Matches Rust's mt_20. */
  mt20?: boolean | null | undefined;
  /** Matches Rust's mt_24. */
  mt24?: boolean | null | undefined;
  /** Matches Rust's mt_3. */
  mt3?: boolean | null | undefined;
  /** Matches Rust's mt_32. */
  mt32?: boolean | null | undefined;
  /** Matches Rust's mt_4. */
  mt4?: boolean | null | undefined;
  /** Matches Rust's mt_5. */
  mt5?: boolean | null | undefined;
  /** Matches Rust's mt_6. */
  mt6?: boolean | null | undefined;
  /** Matches Rust's mt_8. */
  mt8?: boolean | null | undefined;
  /** Matches Rust's mt_auto. */
  mtAuto?: boolean | null | undefined;
  /** Matches Rust's mx_0. */
  mx0?: boolean | null | undefined;
  /** Matches Rust's mx_1. */
  mx1?: boolean | null | undefined;
  /** Matches Rust's mx_10. */
  mx10?: boolean | null | undefined;
  /** Matches Rust's mx_12. */
  mx12?: boolean | null | undefined;
  /** Matches Rust's mx_16. */
  mx16?: boolean | null | undefined;
  /** Matches Rust's mx_2. */
  mx2?: boolean | null | undefined;
  /** Matches Rust's mx_20. */
  mx20?: boolean | null | undefined;
  /** Matches Rust's mx_24. */
  mx24?: boolean | null | undefined;
  /** Matches Rust's mx_3. */
  mx3?: boolean | null | undefined;
  /** Matches Rust's mx_32. */
  mx32?: boolean | null | undefined;
  /** Matches Rust's mx_4. */
  mx4?: boolean | null | undefined;
  /** Matches Rust's mx_5. */
  mx5?: boolean | null | undefined;
  /** Matches Rust's mx_6. */
  mx6?: boolean | null | undefined;
  /** Matches Rust's mx_8. */
  mx8?: boolean | null | undefined;
  /** Matches Rust's mx_auto. */
  mxAuto?: boolean | null | undefined;
  /** Matches Rust's my_0. */
  my0?: boolean | null | undefined;
  /** Matches Rust's my_1. */
  my1?: boolean | null | undefined;
  /** Matches Rust's my_10. */
  my10?: boolean | null | undefined;
  /** Matches Rust's my_12. */
  my12?: boolean | null | undefined;
  /** Matches Rust's my_16. */
  my16?: boolean | null | undefined;
  /** Matches Rust's my_2. */
  my2?: boolean | null | undefined;
  /** Matches Rust's my_20. */
  my20?: boolean | null | undefined;
  /** Matches Rust's my_24. */
  my24?: boolean | null | undefined;
  /** Matches Rust's my_3. */
  my3?: boolean | null | undefined;
  /** Matches Rust's my_32. */
  my32?: boolean | null | undefined;
  /** Matches Rust's my_4. */
  my4?: boolean | null | undefined;
  /** Matches Rust's my_5. */
  my5?: boolean | null | undefined;
  /** Matches Rust's my_6. */
  my6?: boolean | null | undefined;
  /** Matches Rust's my_8. */
  my8?: boolean | null | undefined;
  /** Matches Rust's my_auto. */
  myAuto?: boolean | null | undefined;
  /** Matches Rust's overflow_hidden. */
  overflowHidden?: boolean | null | undefined;
  /** Matches Rust's overflow_scroll. */
  overflowScroll?: boolean | null | undefined;
  /** Matches Rust's overflow_x_scroll. */
  overflowXScroll?: boolean | null | undefined;
  /** Matches Rust's overflow_y_scroll. */
  overflowYScroll?: boolean | null | undefined;
  /** Matches Rust's p_1. */
  p1?: boolean | null | undefined;
  /** Matches Rust's p_2. */
  p2?: boolean | null | undefined;
  /** Matches Rust's p_3. */
  p3?: boolean | null | undefined;
  /** Matches Rust's p_4. */
  p4?: boolean | null | undefined;
  /** Matches Rust's p_5. */
  p5?: boolean | null | undefined;
  /** Matches Rust's p_6. */
  p6?: boolean | null | undefined;
  /** Matches Rust's px_2. */
  px2?: boolean | null | undefined;
  /** Matches Rust's px_3. */
  px3?: boolean | null | undefined;
  /** Matches Rust's px_4. */
  px4?: boolean | null | undefined;
  /** Matches Rust's py_1. */
  py1?: boolean | null | undefined;
  /** Matches Rust's py_2. */
  py2?: boolean | null | undefined;
  /** Matches Rust's relative. */
  relative?: boolean | null | undefined;
  /** Matches Rust's rounded_2xl. */
  rounded2xl?: boolean | null | undefined;
  /** Matches Rust's rounded_full. */
  roundedFull?: boolean | null | undefined;
  /** Matches Rust's rounded_lg. */
  roundedLg?: boolean | null | undefined;
  /** Matches Rust's rounded_md. */
  roundedMd?: boolean | null | undefined;
  /** Matches Rust's rounded_sm. */
  roundedSm?: boolean | null | undefined;
  /** Matches Rust's rounded_xl. */
  roundedXl?: boolean | null | undefined;
  /** Matches Rust's row_end_auto. */
  rowEndAuto?: boolean | null | undefined;
  /** Matches Rust's row_span_full. */
  rowSpanFull?: boolean | null | undefined;
  /** Matches Rust's row_start_auto. */
  rowStartAuto?: boolean | null | undefined;
  /** Matches Rust's rtl. */
  rtl?: boolean | null | undefined;
  /** Matches Rust's selectable. */
  selectable?: boolean | null | undefined;
  /** Matches Rust's self_baseline. */
  selfBaseline?: boolean | null | undefined;
  /** Matches Rust's self_center. */
  selfCenter?: boolean | null | undefined;
  /** Matches Rust's self_end. */
  selfEnd?: boolean | null | undefined;
  /** Matches Rust's self_flex_end. */
  selfFlexEnd?: boolean | null | undefined;
  /** Matches Rust's self_flex_start. */
  selfFlexStart?: boolean | null | undefined;
  /** Matches Rust's self_start. */
  selfStart?: boolean | null | undefined;
  /** Matches Rust's self_stretch. */
  selfStretch?: boolean | null | undefined;
  /** Matches Rust's size_full. */
  sizeFull?: boolean | null | undefined;
  /** Matches Rust's snap_stop_always. */
  snapStopAlways?: boolean | null | undefined;
  /** Matches Rust's sticky. */
  positionSticky?: boolean | null | undefined;
  /** Matches Rust's text_2xl. */
  text2xl?: boolean | null | undefined;
  /** Matches Rust's text_3xl. */
  text3xl?: boolean | null | undefined;
  /** Matches Rust's text_base. */
  textBase?: boolean | null | undefined;
  /** Matches Rust's text_center. */
  textCenter?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis. */
  textEllipsis?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis_middle. */
  textEllipsisMiddle?: boolean | null | undefined;
  /** Matches Rust's text_ellipsis_start. */
  textEllipsisStart?: boolean | null | undefined;
  /** Matches Rust's text_end. */
  textEnd?: boolean | null | undefined;
  /** Matches Rust's text_justify. */
  textJustify?: boolean | null | undefined;
  /** Matches Rust's text_left. */
  textLeft?: boolean | null | undefined;
  /** Matches Rust's text_lg. */
  textLg?: boolean | null | undefined;
  /** Matches Rust's text_right. */
  textRight?: boolean | null | undefined;
  /** Matches Rust's text_sm. */
  textSm?: boolean | null | undefined;
  /** Matches Rust's text_start. */
  textStart?: boolean | null | undefined;
  /** Matches Rust's text_xl. */
  textXl?: boolean | null | undefined;
  /** Matches Rust's text_xs. */
  textXs?: boolean | null | undefined;
  /** Matches Rust's truncate. */
  truncate?: boolean | null | undefined;
  /** Matches Rust's user_select_none. */
  userSelectNone?: boolean | null | undefined;
  /** Matches Rust's user_select_text. */
  userSelectText?: boolean | null | undefined;
  /** Matches Rust's visible. */
  visible?: boolean | null | undefined;
  /** Matches Rust's w_full. */
  wFull?: boolean | null | undefined;
  /** Matches Rust's whitespace_normal. */
  whitespaceNormal?: boolean | null | undefined;
  /** Matches Rust's whitespace_nowrap. */
  whitespaceNowrap?: boolean | null | undefined;
}

export type HelperDeclaration = Record<string, unknown>;
export interface StyleHelperDefinition {
  fields: readonly string[];
  resolve: () => HelperDeclaration;
}

export const styleHelpers: Record<string, StyleHelperDefinition> = {
  absolute: { fields: ["position"], resolve: () => ({ position: "absolute" }) },
  appRegionDrag: { fields: ["appRegion"], resolve: () => ({ appRegion: "drag" }) },
  appRegionNoDrag: { fields: ["appRegion"], resolve: () => ({ appRegion: "no-drag" }) },
  aspectSquare: { fields: ["aspectRatio"], resolve: () => ({ aspectRatio: 1 }) },
  block: { fields: ["display"], resolve: () => ({ display: "block" }) },
  borderDashed: { fields: ["borderStyle"], resolve: () => ({ borderStyle: "dashed" }) },
  borderDotted: { fields: ["borderStyle"], resolve: () => ({ borderStyle: "dotted" }) },
  borderSolid: { fields: ["borderStyle"], resolve: () => ({ borderStyle: "solid" }) },
  colEndAuto: { fields: ["gridColumnEnd"], resolve: () => ({ gridColumnEnd: 0 }) },
  colSpanFull: {
    fields: ["gridColumnSpan", "gridColumnStart", "gridColumnEnd"],
    resolve: () => ({ gridColumnSpan: null, gridColumnStart: 1, gridColumnEnd: -1 }),
  },
  colStartAuto: { fields: ["gridColumnStart"], resolve: () => ({ gridColumnStart: 0 }) },
  contentAround: { fields: ["alignContent"], resolve: () => ({ alignContent: "space-around" }) },
  contentBetween: { fields: ["alignContent"], resolve: () => ({ alignContent: "space-between" }) },
  contentCenter: { fields: ["alignContent"], resolve: () => ({ alignContent: "center" }) },
  contentEnd: { fields: ["alignContent"], resolve: () => ({ alignContent: "flex-end" }) },
  contentEvenly: { fields: ["alignContent"], resolve: () => ({ alignContent: "space-evenly" }) },
  contentNormal: { fields: ["alignContent"], resolve: () => ({ alignContent: "normal" }) },
  contentStart: { fields: ["alignContent"], resolve: () => ({ alignContent: "flex-start" }) },
  contentStretch: { fields: ["alignContent"], resolve: () => ({ alignContent: "stretch" }) },
  cursorAlias: { fields: ["cursor"], resolve: () => ({ cursor: "alias" }) },
  cursorColResize: { fields: ["cursor"], resolve: () => ({ cursor: "col-resize" }) },
  cursorContextMenu: { fields: ["cursor"], resolve: () => ({ cursor: "context-menu" }) },
  cursorCopy: { fields: ["cursor"], resolve: () => ({ cursor: "copy" }) },
  cursorCrosshair: { fields: ["cursor"], resolve: () => ({ cursor: "crosshair" }) },
  cursorDefault: { fields: ["cursor"], resolve: () => ({ cursor: "default" }) },
  cursorEResize: { fields: ["cursor"], resolve: () => ({ cursor: "e-resize" }) },
  cursorEwResize: { fields: ["cursor"], resolve: () => ({ cursor: "ew-resize" }) },
  cursorGrab: { fields: ["cursor"], resolve: () => ({ cursor: "grab" }) },
  cursorGrabbing: { fields: ["cursor"], resolve: () => ({ cursor: "grabbing" }) },
  cursorMove: { fields: ["cursor"], resolve: () => ({ cursor: "grabbing" }) },
  cursorNResize: { fields: ["cursor"], resolve: () => ({ cursor: "n-resize" }) },
  cursorNeswResize: { fields: ["cursor"], resolve: () => ({ cursor: "nesw-resize" }) },
  cursorNoDrop: { fields: ["cursor"], resolve: () => ({ cursor: "not-allowed" }) },
  cursorNotAllowed: { fields: ["cursor"], resolve: () => ({ cursor: "not-allowed" }) },
  cursorNsResize: { fields: ["cursor"], resolve: () => ({ cursor: "ns-resize" }) },
  cursorNwseResize: { fields: ["cursor"], resolve: () => ({ cursor: "nwse-resize" }) },
  cursorPointer: { fields: ["cursor"], resolve: () => ({ cursor: "pointer" }) },
  cursorRowResize: { fields: ["cursor"], resolve: () => ({ cursor: "row-resize" }) },
  cursorSResize: { fields: ["cursor"], resolve: () => ({ cursor: "s-resize" }) },
  cursorText: { fields: ["cursor"], resolve: () => ({ cursor: "text" }) },
  cursorVerticalText: { fields: ["cursor"], resolve: () => ({ cursor: "vertical-text" }) },
  cursorWResize: { fields: ["cursor"], resolve: () => ({ cursor: "w-resize" }) },
  flex: { fields: ["display"], resolve: () => ({ display: "flex" }) },
  flex1: {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 1, flexShrink: 1, flexBasis: 0 }),
  },
  flexAuto: {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 1, flexShrink: 1, flexBasis: "auto" }),
  },
  flexBasisAuto: { fields: ["flexBasis"], resolve: () => ({ flexBasis: "auto" }) },
  flexCol: {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "column" }),
  },
  flexColReverse: {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "column-reverse" }),
  },
  flexGrow0: { fields: ["flexGrow"], resolve: () => ({ flexGrow: 0 }) },
  flexGrow1: { fields: ["flexGrow"], resolve: () => ({ flexGrow: 1 }) },
  flexInitial: {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 0, flexShrink: 1, flexBasis: "auto" }),
  },
  flexNone: {
    fields: ["flexGrow", "flexShrink", "flexBasis"],
    resolve: () => ({ flexGrow: 0, flexShrink: 0, flexBasis: "auto" }),
  },
  flexNowrap: { fields: ["flexWrap"], resolve: () => ({ flexWrap: "nowrap" }) },
  flexRow: {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "row" }),
  },
  flexRowReverse: {
    fields: ["display", "flexDirection"],
    resolve: () => ({ display: "flex", flexDirection: "row-reverse" }),
  },
  flexShrink0: { fields: ["flexShrink"], resolve: () => ({ flexShrink: 0 }) },
  flexShrink1: { fields: ["flexShrink"], resolve: () => ({ flexShrink: 1 }) },
  flexWrap: { fields: ["flexWrap"], resolve: () => ({ flexWrap: "wrap" }) },
  flexWrapReverse: { fields: ["flexWrap"], resolve: () => ({ flexWrap: "wrap-reverse" }) },
  fontBold: { fields: ["fontWeight"], resolve: () => ({ fontWeight: 700 }) },
  fontMedium: { fields: ["fontWeight"], resolve: () => ({ fontWeight: 500 }) },
  fontNormal: { fields: ["fontWeight"], resolve: () => ({ fontWeight: 400 }) },
  fontSemibold: { fields: ["fontWeight"], resolve: () => ({ fontWeight: 600 }) },
  gap1: { fields: ["gap"], resolve: () => ({ gap: 4 }) },
  gap2: { fields: ["gap"], resolve: () => ({ gap: 8 }) },
  gap3: { fields: ["gap"], resolve: () => ({ gap: 12 }) },
  gap4: { fields: ["gap"], resolve: () => ({ gap: 16 }) },
  gap5: { fields: ["gap"], resolve: () => ({ gap: 20 }) },
  gap6: { fields: ["gap"], resolve: () => ({ gap: 24 }) },
  gapX0: { fields: ["columnGap"], resolve: () => ({ columnGap: 0 }) },
  gapX1: { fields: ["columnGap"], resolve: () => ({ columnGap: 4 }) },
  gapX2: { fields: ["columnGap"], resolve: () => ({ columnGap: 8 }) },
  gapX3: { fields: ["columnGap"], resolve: () => ({ columnGap: 12 }) },
  gapX4: { fields: ["columnGap"], resolve: () => ({ columnGap: 16 }) },
  gapX5: { fields: ["columnGap"], resolve: () => ({ columnGap: 20 }) },
  gapX6: { fields: ["columnGap"], resolve: () => ({ columnGap: 24 }) },
  gapY0: { fields: ["rowGap"], resolve: () => ({ rowGap: 0 }) },
  gapY1: { fields: ["rowGap"], resolve: () => ({ rowGap: 4 }) },
  gapY2: { fields: ["rowGap"], resolve: () => ({ rowGap: 8 }) },
  gapY3: { fields: ["rowGap"], resolve: () => ({ rowGap: 12 }) },
  gapY4: { fields: ["rowGap"], resolve: () => ({ rowGap: 16 }) },
  gapY5: { fields: ["rowGap"], resolve: () => ({ rowGap: 20 }) },
  gapY6: { fields: ["rowGap"], resolve: () => ({ rowGap: 24 }) },
  grid: { fields: ["display"], resolve: () => ({ display: "grid" }) },
  gridFlowCol: { fields: ["gridAutoFlow"], resolve: () => ({ gridAutoFlow: "column" }) },
  gridFlowColDense: { fields: ["gridAutoFlow"], resolve: () => ({ gridAutoFlow: "column dense" }) },
  gridFlowRow: { fields: ["gridAutoFlow"], resolve: () => ({ gridAutoFlow: "row" }) },
  gridFlowRowDense: { fields: ["gridAutoFlow"], resolve: () => ({ gridAutoFlow: "row dense" }) },
  h10: { fields: ["height"], resolve: () => ({ height: 40 }) },
  h12: { fields: ["height"], resolve: () => ({ height: 48 }) },
  h8: { fields: ["height"], resolve: () => ({ height: 32 }) },
  hFull: { fields: ["height"], resolve: () => ({ height: "100%" }) },
  hidden: { fields: ["display"], resolve: () => ({ display: "none" }) },
  inset0: {
    fields: ["top", "right", "bottom", "left"],
    resolve: () => ({ top: 0, right: 0, bottom: 0, left: 0 }),
  },
  invisible: { fields: ["visibility"], resolve: () => ({ visibility: "hidden" }) },
  itemsBaseline: { fields: ["alignItems"], resolve: () => ({ alignItems: "baseline" }) },
  itemsCenter: { fields: ["alignItems"], resolve: () => ({ alignItems: "center" }) },
  itemsEnd: { fields: ["alignItems"], resolve: () => ({ alignItems: "flex-end" }) },
  itemsStart: { fields: ["alignItems"], resolve: () => ({ alignItems: "flex-start" }) },
  itemsStretch: { fields: ["alignItems"], resolve: () => ({ alignItems: "stretch" }) },
  justifyAround: {
    fields: ["justifyContent"],
    resolve: () => ({ justifyContent: "space-around" }),
  },
  justifyBetween: {
    fields: ["justifyContent"],
    resolve: () => ({ justifyContent: "space-between" }),
  },
  justifyCenter: { fields: ["justifyContent"], resolve: () => ({ justifyContent: "center" }) },
  justifyEnd: { fields: ["justifyContent"], resolve: () => ({ justifyContent: "end" }) },
  justifyEvenly: {
    fields: ["justifyContent"],
    resolve: () => ({ justifyContent: "space-evenly" }),
  },
  justifyStart: { fields: ["justifyContent"], resolve: () => ({ justifyContent: "start" }) },
  ltr: { fields: ["direction"], resolve: () => ({ direction: "ltr" }) },
  m0: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 }),
  },
  m1: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 4, marginRight: 4, marginBottom: 4, marginLeft: 4 }),
  },
  m10: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 40, marginRight: 40, marginBottom: 40, marginLeft: 40 }),
  },
  m12: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 48, marginRight: 48, marginBottom: 48, marginLeft: 48 }),
  },
  m16: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 64, marginRight: 64, marginBottom: 64, marginLeft: 64 }),
  },
  m2: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 8, marginRight: 8, marginBottom: 8, marginLeft: 8 }),
  },
  m20: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 80, marginRight: 80, marginBottom: 80, marginLeft: 80 }),
  },
  m24: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 96, marginRight: 96, marginBottom: 96, marginLeft: 96 }),
  },
  m3: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 12, marginRight: 12, marginBottom: 12, marginLeft: 12 }),
  },
  m32: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 128, marginRight: 128, marginBottom: 128, marginLeft: 128 }),
  },
  m4: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 16, marginRight: 16, marginBottom: 16, marginLeft: 16 }),
  },
  m5: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 20, marginRight: 20, marginBottom: 20, marginLeft: 20 }),
  },
  m6: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 24, marginRight: 24, marginBottom: 24, marginLeft: 24 }),
  },
  m8: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({ marginTop: 32, marginRight: 32, marginBottom: 32, marginLeft: 32 }),
  },
  mAuto: {
    fields: ["marginTop", "marginRight", "marginBottom", "marginLeft"],
    resolve: () => ({
      marginTop: "auto",
      marginRight: "auto",
      marginBottom: "auto",
      marginLeft: "auto",
    }),
  },
  mb0: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 0 }) },
  mb1: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 4 }) },
  mb10: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 40 }) },
  mb12: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 48 }) },
  mb16: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 64 }) },
  mb2: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 8 }) },
  mb20: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 80 }) },
  mb24: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 96 }) },
  mb3: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 12 }) },
  mb32: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 128 }) },
  mb4: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 16 }) },
  mb5: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 20 }) },
  mb6: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 24 }) },
  mb8: { fields: ["marginBottom"], resolve: () => ({ marginBottom: 32 }) },
  mbAuto: { fields: ["marginBottom"], resolve: () => ({ marginBottom: "auto" }) },
  ml0: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 0 }) },
  ml1: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 4 }) },
  ml10: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 40 }) },
  ml12: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 48 }) },
  ml16: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 64 }) },
  ml2: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 8 }) },
  ml20: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 80 }) },
  ml24: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 96 }) },
  ml3: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 12 }) },
  ml32: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 128 }) },
  ml4: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 16 }) },
  ml5: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 20 }) },
  ml6: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 24 }) },
  ml8: { fields: ["marginLeft"], resolve: () => ({ marginLeft: 32 }) },
  mlAuto: { fields: ["marginLeft"], resolve: () => ({ marginLeft: "auto" }) },
  mr0: { fields: ["marginRight"], resolve: () => ({ marginRight: 0 }) },
  mr1: { fields: ["marginRight"], resolve: () => ({ marginRight: 4 }) },
  mr10: { fields: ["marginRight"], resolve: () => ({ marginRight: 40 }) },
  mr12: { fields: ["marginRight"], resolve: () => ({ marginRight: 48 }) },
  mr16: { fields: ["marginRight"], resolve: () => ({ marginRight: 64 }) },
  mr2: { fields: ["marginRight"], resolve: () => ({ marginRight: 8 }) },
  mr20: { fields: ["marginRight"], resolve: () => ({ marginRight: 80 }) },
  mr24: { fields: ["marginRight"], resolve: () => ({ marginRight: 96 }) },
  mr3: { fields: ["marginRight"], resolve: () => ({ marginRight: 12 }) },
  mr32: { fields: ["marginRight"], resolve: () => ({ marginRight: 128 }) },
  mr4: { fields: ["marginRight"], resolve: () => ({ marginRight: 16 }) },
  mr5: { fields: ["marginRight"], resolve: () => ({ marginRight: 20 }) },
  mr6: { fields: ["marginRight"], resolve: () => ({ marginRight: 24 }) },
  mr8: { fields: ["marginRight"], resolve: () => ({ marginRight: 32 }) },
  mrAuto: { fields: ["marginRight"], resolve: () => ({ marginRight: "auto" }) },
  mt0: { fields: ["marginTop"], resolve: () => ({ marginTop: 0 }) },
  mt1: { fields: ["marginTop"], resolve: () => ({ marginTop: 4 }) },
  mt10: { fields: ["marginTop"], resolve: () => ({ marginTop: 40 }) },
  mt12: { fields: ["marginTop"], resolve: () => ({ marginTop: 48 }) },
  mt16: { fields: ["marginTop"], resolve: () => ({ marginTop: 64 }) },
  mt2: { fields: ["marginTop"], resolve: () => ({ marginTop: 8 }) },
  mt20: { fields: ["marginTop"], resolve: () => ({ marginTop: 80 }) },
  mt24: { fields: ["marginTop"], resolve: () => ({ marginTop: 96 }) },
  mt3: { fields: ["marginTop"], resolve: () => ({ marginTop: 12 }) },
  mt32: { fields: ["marginTop"], resolve: () => ({ marginTop: 128 }) },
  mt4: { fields: ["marginTop"], resolve: () => ({ marginTop: 16 }) },
  mt5: { fields: ["marginTop"], resolve: () => ({ marginTop: 20 }) },
  mt6: { fields: ["marginTop"], resolve: () => ({ marginTop: 24 }) },
  mt8: { fields: ["marginTop"], resolve: () => ({ marginTop: 32 }) },
  mtAuto: { fields: ["marginTop"], resolve: () => ({ marginTop: "auto" }) },
  mx0: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 0, marginRight: 0 }),
  },
  mx1: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 4, marginRight: 4 }),
  },
  mx10: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 40, marginRight: 40 }),
  },
  mx12: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 48, marginRight: 48 }),
  },
  mx16: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 64, marginRight: 64 }),
  },
  mx2: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 8, marginRight: 8 }),
  },
  mx20: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 80, marginRight: 80 }),
  },
  mx24: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 96, marginRight: 96 }),
  },
  mx3: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 12, marginRight: 12 }),
  },
  mx32: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 128, marginRight: 128 }),
  },
  mx4: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 16, marginRight: 16 }),
  },
  mx5: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 20, marginRight: 20 }),
  },
  mx6: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 24, marginRight: 24 }),
  },
  mx8: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: 32, marginRight: 32 }),
  },
  mxAuto: {
    fields: ["marginLeft", "marginRight"],
    resolve: () => ({ marginLeft: "auto", marginRight: "auto" }),
  },
  my0: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 0, marginBottom: 0 }),
  },
  my1: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 4, marginBottom: 4 }),
  },
  my10: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 40, marginBottom: 40 }),
  },
  my12: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 48, marginBottom: 48 }),
  },
  my16: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 64, marginBottom: 64 }),
  },
  my2: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 8, marginBottom: 8 }),
  },
  my20: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 80, marginBottom: 80 }),
  },
  my24: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 96, marginBottom: 96 }),
  },
  my3: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 12, marginBottom: 12 }),
  },
  my32: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 128, marginBottom: 128 }),
  },
  my4: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 16, marginBottom: 16 }),
  },
  my5: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 20, marginBottom: 20 }),
  },
  my6: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 24, marginBottom: 24 }),
  },
  my8: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: 32, marginBottom: 32 }),
  },
  myAuto: {
    fields: ["marginTop", "marginBottom"],
    resolve: () => ({ marginTop: "auto", marginBottom: "auto" }),
  },
  overflowHidden: {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "hidden", overflowY: "hidden" }),
  },
  overflowScroll: {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "scroll", overflowY: "scroll" }),
  },
  overflowXScroll: {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "scroll", overflowY: "hidden" }),
  },
  overflowYScroll: {
    fields: ["overflowX", "overflowY"],
    resolve: () => ({ overflowX: "hidden", overflowY: "scroll" }),
  },
  p1: {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 4, paddingRight: 4, paddingBottom: 4, paddingLeft: 4 }),
  },
  p2: {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 8, paddingRight: 8, paddingBottom: 8, paddingLeft: 8 }),
  },
  p3: {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 12, paddingRight: 12, paddingBottom: 12, paddingLeft: 12 }),
  },
  p4: {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 16, paddingRight: 16, paddingBottom: 16, paddingLeft: 16 }),
  },
  p5: {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20 }),
  },
  p6: {
    fields: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
    resolve: () => ({ paddingTop: 24, paddingRight: 24, paddingBottom: 24, paddingLeft: 24 }),
  },
  px2: {
    fields: ["paddingLeft", "paddingRight"],
    resolve: () => ({ paddingLeft: 8, paddingRight: 8 }),
  },
  px3: {
    fields: ["paddingLeft", "paddingRight"],
    resolve: () => ({ paddingLeft: 12, paddingRight: 12 }),
  },
  px4: {
    fields: ["paddingLeft", "paddingRight"],
    resolve: () => ({ paddingLeft: 16, paddingRight: 16 }),
  },
  py1: {
    fields: ["paddingTop", "paddingBottom"],
    resolve: () => ({ paddingTop: 4, paddingBottom: 4 }),
  },
  py2: {
    fields: ["paddingTop", "paddingBottom"],
    resolve: () => ({ paddingTop: 8, paddingBottom: 8 }),
  },
  relative: { fields: ["position"], resolve: () => ({ position: "relative" }) },
  rounded2xl: {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 16,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  roundedFull: {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 4096,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  roundedLg: {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 8,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  roundedMd: {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 6,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  roundedSm: {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 4,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  roundedXl: {
    fields: [
      "borderRadius",
      "borderTopLeftRadius",
      "borderTopRightRadius",
      "borderBottomLeftRadius",
      "borderBottomRightRadius",
    ],
    resolve: () => ({
      borderRadius: 12,
      borderTopLeftRadius: null,
      borderTopRightRadius: null,
      borderBottomLeftRadius: null,
      borderBottomRightRadius: null,
    }),
  },
  rowEndAuto: { fields: ["gridRowEnd"], resolve: () => ({ gridRowEnd: 0 }) },
  rowSpanFull: {
    fields: ["gridRowSpan", "gridRowStart", "gridRowEnd"],
    resolve: () => ({ gridRowSpan: null, gridRowStart: 1, gridRowEnd: -1 }),
  },
  rowStartAuto: { fields: ["gridRowStart"], resolve: () => ({ gridRowStart: 0 }) },
  rtl: { fields: ["direction"], resolve: () => ({ direction: "rtl" }) },
  selectable: { fields: ["userSelect"], resolve: () => ({ userSelect: "text" }) },
  selfBaseline: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "baseline" }) },
  selfCenter: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "center" }) },
  selfEnd: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "end" }) },
  selfFlexEnd: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "flex-end" }) },
  selfFlexStart: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "flex-start" }) },
  selfStart: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "start" }) },
  selfStretch: { fields: ["alignSelf"], resolve: () => ({ alignSelf: "stretch" }) },
  sizeFull: { fields: ["width", "height"], resolve: () => ({ width: "100%", height: "100%" }) },
  snapStopAlways: { fields: ["scrollSnapStop"], resolve: () => ({ scrollSnapStop: "always" }) },
  positionSticky: { fields: ["position"], resolve: () => ({ position: "sticky" }) },
  text2xl: {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 24, lineHeight: 32 }),
  },
  text3xl: {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 30, lineHeight: 36 }),
  },
  textBase: {
    fields: ["fontSize", "lineHeight"],
    resolve: () => ({ fontSize: 16, lineHeight: 24 }),
  },
  textCenter: { fields: ["textAlign"], resolve: () => ({ textAlign: "center" }) },
  textEllipsis: { fields: ["textOverflow"], resolve: () => ({ textOverflow: "ellipsis" }) },
  textEllipsisMiddle: {
    fields: ["textOverflow"],
    resolve: () => ({ textOverflow: "ellipsis-middle" }),
  },
  textEllipsisStart: {
    fields: ["textOverflow"],
    resolve: () => ({ textOverflow: "ellipsis-start" }),
  },
  textEnd: { fields: ["textAlign"], resolve: () => ({ textAlign: "end" }) },
  textJustify: { fields: ["textAlign"], resolve: () => ({ textAlign: "justify" }) },
  textLeft: { fields: ["textAlign"], resolve: () => ({ textAlign: "left" }) },
  textLg: { fields: ["fontSize", "lineHeight"], resolve: () => ({ fontSize: 18, lineHeight: 26 }) },
  textRight: { fields: ["textAlign"], resolve: () => ({ textAlign: "right" }) },
  textSm: { fields: ["fontSize", "lineHeight"], resolve: () => ({ fontSize: 14, lineHeight: 20 }) },
  textStart: { fields: ["textAlign"], resolve: () => ({ textAlign: "start" }) },
  textXl: { fields: ["fontSize", "lineHeight"], resolve: () => ({ fontSize: 20, lineHeight: 28 }) },
  textXs: { fields: ["fontSize", "lineHeight"], resolve: () => ({ fontSize: 12, lineHeight: 16 }) },
  truncate: {
    fields: ["overflowX", "overflowY", "whiteSpace", "textOverflow"],
    resolve: () => ({
      overflowX: "hidden",
      overflowY: "hidden",
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
    }),
  },
  userSelectNone: { fields: ["userSelect"], resolve: () => ({ userSelect: "none" }) },
  userSelectText: { fields: ["userSelect"], resolve: () => ({ userSelect: "text" }) },
  visible: { fields: ["visibility"], resolve: () => ({ visibility: "visible" }) },
  wFull: { fields: ["width"], resolve: () => ({ width: "100%" }) },
  whitespaceNormal: { fields: ["whiteSpace"], resolve: () => ({ whiteSpace: "normal" }) },
  whitespaceNowrap: { fields: ["whiteSpace"], resolve: () => ({ whiteSpace: "nowrap" }) },
};

export const helperProperties = new Set(
  Object.values(styleHelpers).flatMap((helper) => helper.fields),
);

/** Names rejected as direct JSX styling; use the style prop instead. */
export const directStyleNames = new Set([
  "absolute",
  "appRegionDrag",
  "appRegionNoDrag",
  "aspectSquare",
  "block",
  "borderDashed",
  "borderDotted",
  "borderSolid",
  "colEndAuto",
  "colSpanFull",
  "colStartAuto",
  "contentAround",
  "contentBetween",
  "contentCenter",
  "contentEnd",
  "contentEvenly",
  "contentNormal",
  "contentStart",
  "contentStretch",
  "cursorAlias",
  "cursorColResize",
  "cursorContextMenu",
  "cursorCopy",
  "cursorCrosshair",
  "cursorDefault",
  "cursorEResize",
  "cursorEwResize",
  "cursorGrab",
  "cursorGrabbing",
  "cursorMove",
  "cursorNResize",
  "cursorNeswResize",
  "cursorNoDrop",
  "cursorNotAllowed",
  "cursorNsResize",
  "cursorNwseResize",
  "cursorPointer",
  "cursorRowResize",
  "cursorSResize",
  "cursorText",
  "cursorVerticalText",
  "cursorWResize",
  "flex",
  "flex1",
  "flexAuto",
  "flexBasisAuto",
  "flexCol",
  "flexColReverse",
  "flexGrow0",
  "flexGrow1",
  "flexInitial",
  "flexNone",
  "flexNowrap",
  "flexRow",
  "flexRowReverse",
  "flexShrink0",
  "flexShrink1",
  "flexWrap",
  "flexWrapReverse",
  "fontBold",
  "fontMedium",
  "fontNormal",
  "fontSemibold",
  "gap1",
  "gap2",
  "gap3",
  "gap4",
  "gap5",
  "gap6",
  "gapX0",
  "gapX1",
  "gapX2",
  "gapX3",
  "gapX4",
  "gapX5",
  "gapX6",
  "gapY0",
  "gapY1",
  "gapY2",
  "gapY3",
  "gapY4",
  "gapY5",
  "gapY6",
  "grid",
  "gridFlowCol",
  "gridFlowColDense",
  "gridFlowRow",
  "gridFlowRowDense",
  "h10",
  "h12",
  "h8",
  "hFull",
  "hidden",
  "inset0",
  "invisible",
  "itemsBaseline",
  "itemsCenter",
  "itemsEnd",
  "itemsStart",
  "itemsStretch",
  "justifyAround",
  "justifyBetween",
  "justifyCenter",
  "justifyEnd",
  "justifyEvenly",
  "justifyStart",
  "ltr",
  "m0",
  "m1",
  "m10",
  "m12",
  "m16",
  "m2",
  "m20",
  "m24",
  "m3",
  "m32",
  "m4",
  "m5",
  "m6",
  "m8",
  "mAuto",
  "mb0",
  "mb1",
  "mb10",
  "mb12",
  "mb16",
  "mb2",
  "mb20",
  "mb24",
  "mb3",
  "mb32",
  "mb4",
  "mb5",
  "mb6",
  "mb8",
  "mbAuto",
  "ml0",
  "ml1",
  "ml10",
  "ml12",
  "ml16",
  "ml2",
  "ml20",
  "ml24",
  "ml3",
  "ml32",
  "ml4",
  "ml5",
  "ml6",
  "ml8",
  "mlAuto",
  "mr0",
  "mr1",
  "mr10",
  "mr12",
  "mr16",
  "mr2",
  "mr20",
  "mr24",
  "mr3",
  "mr32",
  "mr4",
  "mr5",
  "mr6",
  "mr8",
  "mrAuto",
  "mt0",
  "mt1",
  "mt10",
  "mt12",
  "mt16",
  "mt2",
  "mt20",
  "mt24",
  "mt3",
  "mt32",
  "mt4",
  "mt5",
  "mt6",
  "mt8",
  "mtAuto",
  "mx0",
  "mx1",
  "mx10",
  "mx12",
  "mx16",
  "mx2",
  "mx20",
  "mx24",
  "mx3",
  "mx32",
  "mx4",
  "mx5",
  "mx6",
  "mx8",
  "mxAuto",
  "my0",
  "my1",
  "my10",
  "my12",
  "my16",
  "my2",
  "my20",
  "my24",
  "my3",
  "my32",
  "my4",
  "my5",
  "my6",
  "my8",
  "myAuto",
  "overflowHidden",
  "overflowScroll",
  "overflowXScroll",
  "overflowYScroll",
  "p1",
  "p2",
  "p3",
  "p4",
  "p5",
  "p6",
  "px2",
  "px3",
  "px4",
  "py1",
  "py2",
  "relative",
  "rounded2xl",
  "roundedFull",
  "roundedLg",
  "roundedMd",
  "roundedSm",
  "roundedXl",
  "rowEndAuto",
  "rowSpanFull",
  "rowStartAuto",
  "rtl",
  "selectable",
  "selfBaseline",
  "selfCenter",
  "selfEnd",
  "selfFlexEnd",
  "selfFlexStart",
  "selfStart",
  "selfStretch",
  "sizeFull",
  "snapStopAlways",
  "positionSticky",
  "text2xl",
  "text3xl",
  "textBase",
  "textCenter",
  "textEllipsis",
  "textEllipsisMiddle",
  "textEllipsisStart",
  "textEnd",
  "textJustify",
  "textLeft",
  "textLg",
  "textRight",
  "textSm",
  "textStart",
  "textXl",
  "textXs",
  "truncate",
  "userSelectNone",
  "userSelectText",
  "visible",
  "wFull",
  "whitespaceNormal",
  "whitespaceNowrap",
  "app-region-drag",
  "app-region-no-drag",
  "aspect-square",
  "border-dashed",
  "border-dotted",
  "border-solid",
  "col-end-auto",
  "col-span-full",
  "col-start-auto",
  "content-around",
  "content-between",
  "content-center",
  "content-end",
  "content-evenly",
  "content-normal",
  "content-start",
  "content-stretch",
  "cursor-alias",
  "cursor-col-resize",
  "cursor-context-menu",
  "cursor-copy",
  "cursor-crosshair",
  "cursor-default",
  "cursor-e-resize",
  "cursor-ew-resize",
  "cursor-grab",
  "cursor-grabbing",
  "cursor-move",
  "cursor-n-resize",
  "cursor-nesw-resize",
  "cursor-no-drop",
  "cursor-not-allowed",
  "cursor-ns-resize",
  "cursor-nwse-resize",
  "cursor-pointer",
  "cursor-row-resize",
  "cursor-s-resize",
  "cursor-text",
  "cursor-vertical-text",
  "cursor-w-resize",
  "flex-1",
  "flex-auto",
  "flex-basis-auto",
  "flex-col",
  "flex-col-reverse",
  "flex-grow-0",
  "flex-grow-1",
  "flex-initial",
  "flex-none",
  "flex-nowrap",
  "flex-row",
  "flex-row-reverse",
  "flex-shrink-0",
  "flex-shrink-1",
  "flex-wrap",
  "flex-wrap-reverse",
  "font-bold",
  "font-medium",
  "font-normal",
  "font-semibold",
  "gap-1",
  "gap-2",
  "gap-3",
  "gap-4",
  "gap-5",
  "gap-6",
  "gap-x-0",
  "gap-x-1",
  "gap-x-2",
  "gap-x-3",
  "gap-x-4",
  "gap-x-5",
  "gap-x-6",
  "gap-y-0",
  "gap-y-1",
  "gap-y-2",
  "gap-y-3",
  "gap-y-4",
  "gap-y-5",
  "gap-y-6",
  "grid-flow-col",
  "grid-flow-col-dense",
  "grid-flow-row",
  "grid-flow-row-dense",
  "h-10",
  "h-12",
  "h-8",
  "h-full",
  "inset-0",
  "items-baseline",
  "items-center",
  "items-end",
  "items-start",
  "items-stretch",
  "justify-around",
  "justify-between",
  "justify-center",
  "justify-end",
  "justify-evenly",
  "justify-start",
  "m-0",
  "m-1",
  "m-10",
  "m-12",
  "m-16",
  "m-2",
  "m-20",
  "m-24",
  "m-3",
  "m-32",
  "m-4",
  "m-5",
  "m-6",
  "m-8",
  "m-auto",
  "mb-0",
  "mb-1",
  "mb-10",
  "mb-12",
  "mb-16",
  "mb-2",
  "mb-20",
  "mb-24",
  "mb-3",
  "mb-32",
  "mb-4",
  "mb-5",
  "mb-6",
  "mb-8",
  "mb-auto",
  "ml-0",
  "ml-1",
  "ml-10",
  "ml-12",
  "ml-16",
  "ml-2",
  "ml-20",
  "ml-24",
  "ml-3",
  "ml-32",
  "ml-4",
  "ml-5",
  "ml-6",
  "ml-8",
  "ml-auto",
  "mr-0",
  "mr-1",
  "mr-10",
  "mr-12",
  "mr-16",
  "mr-2",
  "mr-20",
  "mr-24",
  "mr-3",
  "mr-32",
  "mr-4",
  "mr-5",
  "mr-6",
  "mr-8",
  "mr-auto",
  "mt-0",
  "mt-1",
  "mt-10",
  "mt-12",
  "mt-16",
  "mt-2",
  "mt-20",
  "mt-24",
  "mt-3",
  "mt-32",
  "mt-4",
  "mt-5",
  "mt-6",
  "mt-8",
  "mt-auto",
  "mx-0",
  "mx-1",
  "mx-10",
  "mx-12",
  "mx-16",
  "mx-2",
  "mx-20",
  "mx-24",
  "mx-3",
  "mx-32",
  "mx-4",
  "mx-5",
  "mx-6",
  "mx-8",
  "mx-auto",
  "my-0",
  "my-1",
  "my-10",
  "my-12",
  "my-16",
  "my-2",
  "my-20",
  "my-24",
  "my-3",
  "my-32",
  "my-4",
  "my-5",
  "my-6",
  "my-8",
  "my-auto",
  "overflow-hidden",
  "overflow-scroll",
  "overflow-x-scroll",
  "overflow-y-scroll",
  "p-1",
  "p-2",
  "p-3",
  "p-4",
  "p-5",
  "p-6",
  "px-2",
  "px-3",
  "px-4",
  "py-1",
  "py-2",
  "rounded-2xl",
  "rounded-full",
  "rounded-lg",
  "rounded-md",
  "rounded-sm",
  "rounded-xl",
  "row-end-auto",
  "row-span-full",
  "row-start-auto",
  "self-baseline",
  "self-center",
  "self-end",
  "self-flex-end",
  "self-flex-start",
  "self-start",
  "self-stretch",
  "size-full",
  "snap-stop-always",
  "position-sticky",
  "text-2xl",
  "text-3xl",
  "text-base",
  "text-center",
  "text-ellipsis",
  "text-ellipsis-middle",
  "text-ellipsis-start",
  "text-end",
  "text-justify",
  "text-left",
  "text-lg",
  "text-right",
  "text-sm",
  "text-start",
  "text-xl",
  "text-xs",
  "user-select-none",
  "user-select-text",
  "w-full",
  "whitespace-normal",
  "whitespace-nowrap",
  "textColor",
  "display",
  "flexDirection",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "alignItems",
  "alignSelf",
  "justifyContent",
  "alignContent",
  "gap",
  "columnGap",
  "rowGap",
  "width",
  "height",
  "minWidth",
  "minHeight",
  "maxWidth",
  "maxHeight",
  "padding",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "margin",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "bg",
  "color",
  "hoverColor",
  "activeColor",
  "transition",
  "opacity",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "borderColor",
  "borderRadius",
  "boxShadow",
  "fontSize",
  "fontFamily",
  "fontWeight",
  "lineHeight",
  "textAlign",
  "whiteSpace",
  "textOverflow",
  "lineClamp",
  "overflow",
  "overflowX",
  "overflowY",
  "cursor",
  "appRegion",
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "userSelect",
  "visibility",
  "aspectRatio",
  "gridTemplateColumns",
  "gridTemplateRows",
  "gridAutoFlow",
  "gridColumn",
  "gridRow",
  "gridColumnStart",
  "gridColumnEnd",
  "gridColumnSpan",
  "gridRowStart",
  "gridRowEnd",
  "gridRowSpan",
  "transitionProperty",
  "transitionDuration",
  "transitionTimingFunction",
  "transitionEasing",
  "transitionMaxFps",
  "objectFit",
  "scrollToEndRevision",
  "letterSpacing",
  "wordSpacing",
  "textTransform",
  "textShadow",
  "textDecoration",
  "textDecorationLine",
  "textDecorationColor",
  "textDecorationStyle",
  "textDecorationThickness",
  "wordBreak",
  "overflowWrap",
  "hyphens",
  "textDirection",
  "direction",
  "paddingStart",
  "paddingEnd",
  "marginStart",
  "marginEnd",
  "borderStartWidth",
  "borderEndWidth",
  "bgGradient",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomRightRadius",
  "borderBottomLeftRadius",
  "borderStyle",
  "outline",
  "outlineWidth",
  "outlineColor",
  "outlineOffset",
  "outlineStyle",
  "bgImage",
  "bgSize",
  "bgRepeat",
  "bgPosition",
  "filter",
  "backdropFilter",
  "transform",
  "transformOrigin",
  "mixBlendMode",
  "hoverBg",
  "hoverOutline",
  "hoverTransform",
  "activeBg",
  "activeOutline",
  "activeTransform",
  "focusBg",
  "focusColor",
  "focusOutline",
  "focusTransform",
  "scrollSnapType",
  "scrollSnapAlign",
  "scrollSnapStop",
  "hover",
  "active",
  "focus",
  "dragging",
  "dragOver",
  "groupHover",
  "groupActive",
  "focusWithin",
  "text-color",
  "flex-direction",
  "flex-grow",
  "flex-shrink",
  "flex-basis",
  "align-items",
  "align-self",
  "justify-content",
  "align-content",
  "column-gap",
  "row-gap",
  "min-width",
  "min-height",
  "max-width",
  "max-height",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "hover-color",
  "active-color",
  "border-width",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-color",
  "border-radius",
  "box-shadow",
  "font-size",
  "font-family",
  "font-weight",
  "line-height",
  "text-align",
  "white-space",
  "text-overflow",
  "line-clamp",
  "overflow-x",
  "overflow-y",
  "app-region",
  "user-select",
  "aspect-ratio",
  "grid-template-columns",
  "grid-template-rows",
  "grid-auto-flow",
  "grid-column",
  "grid-row",
  "grid-column-start",
  "grid-column-end",
  "grid-column-span",
  "grid-row-start",
  "grid-row-end",
  "grid-row-span",
  "transition-property",
  "transition-duration",
  "transition-timing-function",
  "transition-easing",
  "transition-max-fps",
  "object-fit",
  "scroll-to-end-revision",
  "letter-spacing",
  "word-spacing",
  "text-transform",
  "text-shadow",
  "text-decoration",
  "text-decoration-line",
  "text-decoration-color",
  "text-decoration-style",
  "text-decoration-thickness",
  "word-break",
  "overflow-wrap",
  "text-direction",
  "padding-start",
  "padding-end",
  "margin-start",
  "margin-end",
  "border-start-width",
  "border-end-width",
  "bg-gradient",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-bottom-right-radius",
  "border-bottom-left-radius",
  "border-style",
  "outline-width",
  "outline-color",
  "outline-offset",
  "outline-style",
  "bg-image",
  "bg-size",
  "bg-repeat",
  "bg-position",
  "backdrop-filter",
  "transform-origin",
  "mix-blend-mode",
  "hover-bg",
  "hover-outline",
  "hover-transform",
  "active-bg",
  "active-outline",
  "active-transform",
  "focus-bg",
  "focus-color",
  "focus-outline",
  "focus-transform",
  "scroll-snap-type",
  "scroll-snap-align",
  "scroll-snap-stop",
  "drag-over",
  "group-hover",
  "group-active",
  "focus-within",
]);
