// Code generated by optionsgen; DO NOT EDIT.

package ui

import "github.com/egoist/quickgui/go/native"

// ObjectFit sets the corresponding style property.
func styleObjectFit(value string) styleOption {
	return func(style *styleData) { style.ObjectFit = value }
}

// WordWrap sets the corresponding style property.
func styleWordWrap(value string) styleOption {
	return func(style *styleData) { style.OverflowWrap = value }
}

// TransitionTimingFunction sets the corresponding style property.
func styleTransitionTimingFunction(value any) styleOption {
	return func(style *styleData) { style.TransitionEasing = value }
}

// PaddingInlineStart sets the corresponding style property.
func stylePaddingInlineStart(value any) styleOption {
	return func(style *styleData) { style.PaddingStart = value }
}

// PaddingInlineEnd sets the corresponding style property.
func stylePaddingInlineEnd(value any) styleOption {
	return func(style *styleData) { style.PaddingEnd = value }
}

// MarginInlineStart sets the corresponding style property.
func styleMarginInlineStart(value any) styleOption {
	return func(style *styleData) { style.MarginStart = value }
}

// MarginInlineEnd sets the corresponding style property.
func styleMarginInlineEnd(value any) styleOption {
	return func(style *styleData) { style.MarginEnd = value }
}

// BorderInlineStartWidth sets the corresponding style property.
func styleBorderInlineStartWidth(value any) styleOption {
	return func(style *styleData) { style.BorderStartWidth = value }
}

// BorderInlineEndWidth sets the corresponding style property.
func styleBorderInlineEndWidth(value any) styleOption {
	return func(style *styleData) { style.BorderEndWidth = value }
}

// AspectRatio sets the corresponding style property.
func styleAspectRatio(value any) styleOption {
	return func(style *styleData) { style.AspectRatio = value }
}

// GridColumn sets the corresponding style property.
func styleGridColumn(value any) styleOption {
	return func(style *styleData) { style.GridColumn = value }
}

// GridRow sets the corresponding style property.
func styleGridRow(value any) styleOption {
	return func(style *styleData) { style.GridRow = value }
}

// BorderStartWidth sets the corresponding style property.
func styleBorderStartWidth(value any) styleOption {
	return func(style *styleData) { style.BorderStartWidth = value }
}

// BorderEndWidth sets the corresponding style property.
func styleBorderEndWidth(value any) styleOption {
	return func(style *styleData) { style.BorderEndWidth = value }
}

// Background sets the corresponding style property.
func styleBackground(value any) styleOption {
	return func(style *styleData) { style.Background = value }
}

// BackgroundGradient sets the corresponding style property.
func styleBackgroundGradient(value any) styleOption {
	return func(style *styleData) { style.BackgroundGradient = value }
}

// TransitionProperty sets the corresponding style property.
func styleTransitionProperty(value any) styleOption {
	return func(style *styleData) { style.TransitionProperty = value }
}

// TransitionDuration sets the corresponding style property.
func styleTransitionDuration(value any) styleOption {
	return func(style *styleData) { style.TransitionDuration = value }
}

// TransitionEasing sets the corresponding style property.
func styleTransitionEasing(value any) styleOption {
	return func(style *styleData) { style.TransitionEasing = value }
}

// TransitionMaxFps sets the corresponding style property.
func styleTransitionMaxFps(value any) styleOption {
	return func(style *styleData) { style.TransitionMaxFps = value }
}

// MarkdownCodeBackground sets the corresponding style property.
func styleMarkdownCodeBackground(value any) styleOption {
	return func(style *styleData) { style.MarkdownCodeBackground = value }
}

// MarkdownBorderColor sets the corresponding style property.
func styleMarkdownBorderColor(value any) styleOption {
	return func(style *styleData) { style.MarkdownBorderColor = value }
}

// MarkdownMutedColor sets the corresponding style property.
func styleMarkdownMutedColor(value any) styleOption {
	return func(style *styleData) { style.MarkdownMutedColor = value }
}

// MarkdownLinkColor sets the corresponding style property.
func styleMarkdownLinkColor(value any) styleOption {
	return func(style *styleData) { style.MarkdownLinkColor = value }
}

// MarkdownCodeTextColor sets the corresponding style property.
func styleMarkdownCodeTextColor(value any) styleOption {
	return func(style *styleData) { style.MarkdownCodeTextColor = value }
}

// MarkdownBlockGap sets the corresponding style property.
func styleMarkdownBlockGap(value any) styleOption {
	return func(style *styleData) { style.MarkdownBlockGap = value }
}

// MarkdownCodeFontSize sets the corresponding style property.
func styleMarkdownCodeFontSize(value any) styleOption {
	return func(style *styleData) { style.MarkdownCodeFontSize = value }
}

// ScrollToEndRevision sets the corresponding style property.
func styleScrollToEndRevision(value any) styleOption {
	return func(style *styleData) { style.ScrollToEndRevision = value }
}

// TextDecoration sets the corresponding style property.
func styleTextDecoration(value string) styleOption {
	return func(style *styleData) { style.TextDecoration = value }
}

// InvalidStyle merges options into the Invalid interaction style.
func styleInvalidStyle(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Invalid, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Invalid = nested
	}
}

// Dragging merges options into the Dragging interaction style.
func styleDragging(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Dragging, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Dragging = nested
	}
}

// DragOver merges options into the DragOver interaction style.
func styleDragOver(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.DragOver, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.DragOver = nested
	}
}

// FocusWithin merges options into the FocusWithin interaction style.
func styleFocusWithin(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.FocusWithin, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.FocusWithin = nested
	}
}

// GridTemplateColumns sets the corresponding style property.
func styleGridTemplateColumns(value any) styleOption {
	return func(style *styleData) { style.GridTemplateColumns = value }
}

// GridTemplateRows sets the corresponding style property.
func styleGridTemplateRows(value any) styleOption {
	return func(style *styleData) { style.GridTemplateRows = value }
}

// GridAutoFlow sets the corresponding style property.
func styleGridAutoFlow(value string) styleOption {
	return func(style *styleData) { style.GridAutoFlow = value }
}

// GridColumnStart sets the corresponding style property.
func styleGridColumnStart(value any) styleOption {
	return func(style *styleData) { style.GridColumnStart = value }
}

// GridColumnEnd sets the corresponding style property.
func styleGridColumnEnd(value any) styleOption {
	return func(style *styleData) { style.GridColumnEnd = value }
}

// GridColumnSpan sets the corresponding style property.
func styleGridColumnSpan(value any) styleOption {
	return func(style *styleData) { style.GridColumnSpan = value }
}

// GridRowStart sets the corresponding style property.
func styleGridRowStart(value any) styleOption {
	return func(style *styleData) { style.GridRowStart = value }
}

// GridRowEnd sets the corresponding style property.
func styleGridRowEnd(value any) styleOption {
	return func(style *styleData) { style.GridRowEnd = value }
}

// GridRowSpan sets the corresponding style property.
func styleGridRowSpan(value any) styleOption {
	return func(style *styleData) { style.GridRowSpan = value }
}

// PaddingStart sets the corresponding style property.
func stylePaddingStart(value any) styleOption {
	return func(style *styleData) { style.PaddingStart = value }
}

// PaddingEnd sets the corresponding style property.
func stylePaddingEnd(value any) styleOption {
	return func(style *styleData) { style.PaddingEnd = value }
}

// MarginStart sets the corresponding style property.
func styleMarginStart(value any) styleOption {
	return func(style *styleData) { style.MarginStart = value }
}

// MarginEnd sets the corresponding style property.
func styleMarginEnd(value any) styleOption {
	return func(style *styleData) { style.MarginEnd = value }
}

// BorderTopWidth sets the corresponding style property.
func styleBorderTopWidth(value any) styleOption {
	return func(style *styleData) { style.BorderTopWidth = value }
}

// BorderRightWidth sets the corresponding style property.
func styleBorderRightWidth(value any) styleOption {
	return func(style *styleData) { style.BorderRightWidth = value }
}

// BorderBottomWidth sets the corresponding style property.
func styleBorderBottomWidth(value any) styleOption {
	return func(style *styleData) { style.BorderBottomWidth = value }
}

// BorderLeftWidth sets the corresponding style property.
func styleBorderLeftWidth(value any) styleOption {
	return func(style *styleData) { style.BorderLeftWidth = value }
}

// BorderTopLeftRadius sets the corresponding style property.
func styleBorderTopLeftRadius(value any) styleOption {
	return func(style *styleData) { style.BorderTopLeftRadius = value }
}

// BorderTopRightRadius sets the corresponding style property.
func styleBorderTopRightRadius(value any) styleOption {
	return func(style *styleData) { style.BorderTopRightRadius = value }
}

// BorderBottomLeftRadius sets the corresponding style property.
func styleBorderBottomLeftRadius(value any) styleOption {
	return func(style *styleData) { style.BorderBottomLeftRadius = value }
}

// BorderBottomRightRadius sets the corresponding style property.
func styleBorderBottomRightRadius(value any) styleOption {
	return func(style *styleData) { style.BorderBottomRightRadius = value }
}

// BorderStyle sets the corresponding style property.
func styleBorderStyle(value string) styleOption {
	return func(style *styleData) { style.BorderStyle = value }
}

// BoxShadow sets the corresponding style property.
func styleBoxShadow(value any) styleOption {
	return func(style *styleData) { style.BoxShadow = value }
}

// TextShadow sets the corresponding style property.
func styleTextShadow(value any) styleOption {
	return func(style *styleData) { style.TextShadow = value }
}

// TextDecorationLine sets the corresponding style property.
func styleTextDecorationLine(value string) styleOption {
	return func(style *styleData) { style.TextDecorationLine = value }
}

// TextDecorationColor sets the corresponding style property.
func styleTextDecorationColor(value any) styleOption {
	return func(style *styleData) { style.TextDecorationColor = value }
}

// TextDecorationStyle sets the corresponding style property.
func styleTextDecorationStyle(value string) styleOption {
	return func(style *styleData) { style.TextDecorationStyle = value }
}

// TextDecorationThickness sets the corresponding style property.
func styleTextDecorationThickness(value any) styleOption {
	return func(style *styleData) { style.TextDecorationThickness = value }
}

// WordSpacing sets the corresponding style property.
func styleWordSpacing(value any) styleOption {
	return func(style *styleData) { style.WordSpacing = value }
}

// WordBreak sets the corresponding style property.
func styleWordBreak(value string) styleOption {
	return func(style *styleData) { style.WordBreak = value }
}

// OverflowWrap sets the corresponding style property.
func styleOverflowWrap(value string) styleOption {
	return func(style *styleData) { style.OverflowWrap = value }
}

// Hyphens sets the corresponding style property.
func styleHyphens(value string) styleOption {
	return func(style *styleData) { style.Hyphens = value }
}

// TextDirection sets the corresponding style property.
func styleTextDirection(value string) styleOption {
	return func(style *styleData) { style.TextDirection = value }
}

// Direction sets the corresponding style property.
func styleDirection(value string) styleOption {
	return func(style *styleData) { style.Direction = value }
}

// BackgroundImage sets the corresponding style property.
func styleBackgroundImage(value string) styleOption {
	return func(style *styleData) { style.BackgroundImage = value }
}

// BackgroundSize sets the corresponding style property.
func styleBackgroundSize(value string) styleOption {
	return func(style *styleData) { style.BackgroundSize = value }
}

// BackgroundRepeat sets the corresponding style property.
func styleBackgroundRepeat(value string) styleOption {
	return func(style *styleData) { style.BackgroundRepeat = value }
}

// BackgroundPosition sets the corresponding style property.
func styleBackgroundPosition(value string) styleOption {
	return func(style *styleData) { style.BackgroundPosition = value }
}

// Filter sets the corresponding style property.
func styleFilter(value any) styleOption {
	return func(style *styleData) { style.Filter = value }
}

// BackdropFilter sets the corresponding style property.
func styleBackdropFilter(value any) styleOption {
	return func(style *styleData) { style.BackdropFilter = value }
}

// MixBlendMode sets the corresponding style property.
func styleMixBlendMode(value string) styleOption {
	return func(style *styleData) { style.MixBlendMode = value }
}

// Transition sets the corresponding style property.
func styleTransition(value any) styleOption {
	return func(style *styleData) { style.Transition = value }
}

// ScrollSnapType sets the corresponding style property.
func styleScrollSnapType(value string) styleOption {
	return func(style *styleData) { style.ScrollSnapType = value }
}

// ScrollSnapX sets the corresponding style property.
func styleScrollSnapX(value string) styleOption {
	return func(style *styleData) { style.ScrollSnapX = value }
}

// ScrollSnapY sets the corresponding style property.
func styleScrollSnapY(value string) styleOption {
	return func(style *styleData) { style.ScrollSnapY = value }
}

// ScrollSnapAlign sets the corresponding style property.
func styleScrollSnapAlign(value string) styleOption {
	return func(style *styleData) { style.ScrollSnapAlign = value }
}

// ScrollSnapStop sets the corresponding style property.
func styleScrollSnapStop(value string) styleOption {
	return func(style *styleData) { style.ScrollSnapStop = value }
}

// Display sets the corresponding style property.
func styleDisplay(value string) styleOption {
	return func(style *styleData) { style.Display = value }
}

// Flex sets the corresponding style property.
func styleFlex(value any) styleOption {
	return func(style *styleData) { style.Flex = value }
}

// FlexDirection sets the corresponding style property.
func styleFlexDirection(value string) styleOption {
	return func(style *styleData) { style.FlexDirection = value }
}

// FlexWrap sets the corresponding style property.
func styleFlexWrap(value string) styleOption {
	return func(style *styleData) { style.FlexWrap = value }
}

// FlexGrow sets the corresponding style property.
func styleFlexGrow(value any) styleOption {
	return func(style *styleData) { style.FlexGrow = value }
}

// FlexShrink sets the corresponding style property.
func styleFlexShrink(value any) styleOption {
	return func(style *styleData) { style.FlexShrink = value }
}

// FlexBasis sets the corresponding style property.
func styleFlexBasis(value any) styleOption {
	return func(style *styleData) { style.FlexBasis = value }
}

// AlignItems sets the corresponding style property.
func styleAlignItems(value string) styleOption {
	return func(style *styleData) { style.AlignItems = value }
}

// AlignSelf sets the corresponding style property.
func styleAlignSelf(value string) styleOption {
	return func(style *styleData) { style.AlignSelf = value }
}

// JustifyContent sets the corresponding style property.
func styleJustifyContent(value string) styleOption {
	return func(style *styleData) { style.JustifyContent = value }
}

// AlignContent sets the corresponding style property.
func styleAlignContent(value string) styleOption {
	return func(style *styleData) { style.AlignContent = value }
}

// Gap sets the corresponding style property.
func styleGap(value any) styleOption {
	return func(style *styleData) { style.Gap = value }
}

// ColumnGap sets the corresponding style property.
func styleColumnGap(value any) styleOption {
	return func(style *styleData) { style.ColumnGap = value }
}

// RowGap sets the corresponding style property.
func styleRowGap(value any) styleOption {
	return func(style *styleData) { style.RowGap = value }
}

// Width sets the corresponding style property.
func styleWidth(value any) styleOption {
	return func(style *styleData) { style.Width = value }
}

// Height sets the corresponding style property.
func styleHeight(value any) styleOption {
	return func(style *styleData) { style.Height = value }
}

// MinWidth sets the corresponding style property.
func styleMinWidth(value any) styleOption {
	return func(style *styleData) { style.MinWidth = value }
}

// MinHeight sets the corresponding style property.
func styleMinHeight(value any) styleOption {
	return func(style *styleData) { style.MinHeight = value }
}

// MaxWidth sets the corresponding style property.
func styleMaxWidth(value any) styleOption {
	return func(style *styleData) { style.MaxWidth = value }
}

// MaxHeight sets the corresponding style property.
func styleMaxHeight(value any) styleOption {
	return func(style *styleData) { style.MaxHeight = value }
}

// Padding sets the corresponding style property.
func stylePadding(value any) styleOption {
	return func(style *styleData) { style.Padding = value }
}

// PaddingTop sets the corresponding style property.
func stylePaddingTop(value any) styleOption {
	return func(style *styleData) { style.PaddingTop = value }
}

// PaddingRight sets the corresponding style property.
func stylePaddingRight(value any) styleOption {
	return func(style *styleData) { style.PaddingRight = value }
}

// PaddingBottom sets the corresponding style property.
func stylePaddingBottom(value any) styleOption {
	return func(style *styleData) { style.PaddingBottom = value }
}

// PaddingLeft sets the corresponding style property.
func stylePaddingLeft(value any) styleOption {
	return func(style *styleData) { style.PaddingLeft = value }
}

// Margin sets the corresponding style property.
func styleMargin(value any) styleOption {
	return func(style *styleData) { style.Margin = value }
}

// MarginTop sets the corresponding style property.
func styleMarginTop(value any) styleOption {
	return func(style *styleData) { style.MarginTop = value }
}

// MarginRight sets the corresponding style property.
func styleMarginRight(value any) styleOption {
	return func(style *styleData) { style.MarginRight = value }
}

// MarginBottom sets the corresponding style property.
func styleMarginBottom(value any) styleOption {
	return func(style *styleData) { style.MarginBottom = value }
}

// MarginLeft sets the corresponding style property.
func styleMarginLeft(value any) styleOption {
	return func(style *styleData) { style.MarginLeft = value }
}

// BackgroundColor sets the corresponding style property.
func styleBackgroundColor(value any) styleOption {
	return func(style *styleData) { style.BackgroundColor = value }
}

// TextColor sets the corresponding style property.
func styleTextColor(value any) styleOption {
	return func(style *styleData) { style.TextColor = value }
}

// Opacity sets the corresponding style property.
func styleOpacity(value any) styleOption {
	return func(style *styleData) { style.Opacity = value }
}

// BorderWidth sets the corresponding style property.
func styleBorderWidth(value any) styleOption {
	return func(style *styleData) { style.BorderWidth = value }
}

// BorderColor sets the corresponding style property.
func styleBorderColor(value any) styleOption {
	return func(style *styleData) { style.BorderColor = value }
}

// BorderRadius sets the corresponding style property.
func styleBorderRadius(value any) styleOption {
	return func(style *styleData) { style.BorderRadius = value }
}

// FontSize sets the corresponding style property.
func styleFontSize(value any) styleOption {
	return func(style *styleData) { style.FontSize = value }
}

// FontFamily sets the corresponding style property.
func styleFontFamily(value string) styleOption {
	return func(style *styleData) { style.FontFamily = value }
}

// FontWeight sets the corresponding style property.
func styleFontWeight(value any) styleOption {
	return func(style *styleData) { style.FontWeight = value }
}

// LineHeight sets the corresponding style property.
func styleLineHeight(value any) styleOption {
	return func(style *styleData) { style.LineHeight = value }
}

// TextAlign sets the corresponding style property.
func styleTextAlign(value string) styleOption {
	return func(style *styleData) { style.TextAlign = value }
}

// Cursor sets the corresponding style property.
func styleCursor(value string) styleOption {
	return func(style *styleData) { style.Cursor = value }
}

// AppRegion sets the corresponding style property.
func styleAppRegion(value string) styleOption {
	return func(style *styleData) { style.AppRegion = value }
}

// UserSelect sets the corresponding style property.
func styleUserSelect(value string) styleOption {
	return func(style *styleData) { style.UserSelect = value }
}

// Position sets the corresponding style property.
func stylePosition(value string) styleOption {
	return func(style *styleData) { style.Position = value }
}

// Overflow sets the corresponding style property.
func styleOverflow(value string) styleOption {
	return func(style *styleData) { style.Overflow = value }
}

// OverflowX sets the corresponding style property.
func styleOverflowX(value string) styleOption {
	return func(style *styleData) { style.OverflowX = value }
}

// OverflowY sets the corresponding style property.
func styleOverflowY(value string) styleOption {
	return func(style *styleData) { style.OverflowY = value }
}

// Visibility sets the corresponding style property.
func styleVisibility(value string) styleOption {
	return func(style *styleData) { style.Visibility = value }
}

// LetterSpacing sets the corresponding style property.
func styleLetterSpacing(value any) styleOption {
	return func(style *styleData) { style.LetterSpacing = value }
}

// TextTransform sets the corresponding style property.
func styleTextTransform(value string) styleOption {
	return func(style *styleData) { style.TextTransform = value }
}

// LineClamp sets the corresponding style property.
func styleLineClamp(value any) styleOption {
	return func(style *styleData) { style.LineClamp = value }
}

// WhiteSpace sets the corresponding style property.
func styleWhiteSpace(value string) styleOption {
	return func(style *styleData) { style.WhiteSpace = value }
}

// TextOverflow sets the corresponding style property.
func styleTextOverflow(value string) styleOption {
	return func(style *styleData) { style.TextOverflow = value }
}

// Top sets the corresponding style property.
func styleTop(value any) styleOption {
	return func(style *styleData) { style.Top = value }
}

// Right sets the corresponding style property.
func styleRight(value any) styleOption {
	return func(style *styleData) { style.Right = value }
}

// Bottom sets the corresponding style property.
func styleBottom(value any) styleOption {
	return func(style *styleData) { style.Bottom = value }
}

// Left sets the corresponding style property.
func styleLeft(value any) styleOption {
	return func(style *styleData) { style.Left = value }
}

// Outline sets the corresponding style property.
func styleOutline(value any) styleOption {
	return func(style *styleData) { style.Outline = value }
}

// OutlineWidth sets the corresponding style property.
func styleOutlineWidth(value any) styleOption {
	return func(style *styleData) { style.OutlineWidth = value }
}

// OutlineColor sets the corresponding style property.
func styleOutlineColor(value any) styleOption {
	return func(style *styleData) { style.OutlineColor = value }
}

// OutlineOffset sets the corresponding style property.
func styleOutlineOffset(value any) styleOption {
	return func(style *styleData) { style.OutlineOffset = value }
}

// OutlineStyle sets the corresponding style property.
func styleOutlineStyle(value string) styleOption {
	return func(style *styleData) { style.OutlineStyle = value }
}

// Transform sets the corresponding style property.
func styleTransform(value any) styleOption {
	return func(style *styleData) { style.Transform = value }
}

// TransformOrigin sets the corresponding style property.
func styleTransformOrigin(value string) styleOption {
	return func(style *styleData) { style.TransformOrigin = value }
}

// Hover merges options into the Hover interaction style.
func styleHover(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Hover, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Hover = nested
	}
}

// Active merges options into the Active interaction style.
func styleActive(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Active, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Active = nested
	}
}

// Focus merges options into the Focus interaction style.
func styleFocus(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Focus, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Focus = nested
	}
}

// DisabledStyle merges options into the Disabled interaction style.
func styleDisabledStyle(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Disabled, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Disabled = nested
	}
}

// SelectedStyle merges options into the Selected interaction style.
func styleSelectedStyle(options ...styleDeclaration) styleOption {
	return func(style *styleData) {
		nested := mergeStateStyles(style.Selected, nil)
		for _, option := range options {
			option.applyStyle(nested)
		}
		style.Selected = nested
	}
}

// OnMouseEnter configures the corresponding node property.
func OnMouseEnter(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnMouseEnter = value })
}

// OnMouseLeave configures the corresponding node property.
func OnMouseLeave(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnMouseLeave = value })
}

// OnInput configures the corresponding node property.
func OnInput(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnInput = value })
}

// OnSubmit configures the corresponding node property.
func OnSubmit(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnSubmit = value })
}

// OnDismiss configures the corresponding node property.
func OnDismiss(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnDismiss = value })
}

// OnStatus configures the corresponding node property.
func OnStatus(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnStatus = value })
}

// OnPointer configures the corresponding node property.
func OnPointer(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnPointer = value })
}

// OnPresentationChange configures the corresponding node property.
func OnPresentationChange(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnPresentationChange = value })
}

// OnSelect configures the corresponding node property.
func OnSelect(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnSelect = value })
}

// OnKeyDown configures the corresponding node property.
func OnKeyDown(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnKeyDown = value })
}

// OnKeyUp configures the corresponding node property.
func OnKeyUp(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnKeyUp = value })
}

// OnMouseDown configures the corresponding node property.
func OnMouseDown(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnMouseDown = value })
}

// OnMouseUp configures the corresponding node property.
func OnMouseUp(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnMouseUp = value })
}

// OnMouseMove configures the corresponding node property.
func OnMouseMove(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnMouseMove = value })
}

// OnDoubleClick configures the corresponding node property.
func OnDoubleClick(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnDoubleClick = value })
}

// OnWheel configures the corresponding node property.
func OnWheel(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnWheel = value })
}

// OnContextMenu configures the corresponding node property.
func OnContextMenu(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnContextMenu = value })
}

// OnPinch configures the corresponding node property.
func OnPinch(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnPinch = value })
}

// OnRotate configures the corresponding node property.
func OnRotate(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnRotate = value })
}

// OnSmartMagnify configures the corresponding node property.
func OnSmartMagnify(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnSmartMagnify = value })
}

// OnPressure configures the corresponding node property.
func OnPressure(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnPressure = value })
}

// OnFocus configures the corresponding node property.
func OnFocus(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnFocus = value })
}

// OnBlur configures the corresponding node property.
func OnBlur(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnBlur = value })
}

// OnAction configures the corresponding node property.
func OnAction(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnAction = value })
}

// OnDragStart configures the corresponding node property.
func OnDragStart(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnDragStart = value })
}

// OnDragEnd configures the corresponding node property.
func OnDragEnd(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnDragEnd = value })
}

// OnDrop configures the corresponding node property.
func OnDrop(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnDrop = value })
}

// OnFilesDropped configures the corresponding node property.
func OnFilesDropped(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnFilesDropped = value })
}

// OnComponentChange configures the corresponding node property.
func OnComponentChange(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnComponentChange = value })
}

// OnCommit configures the corresponding node property.
func OnCommit(value func(*native.Event)) Option {
	return propertyOption(func(props *Props) { props.OnCommit = value })
}

// Disabled configures the corresponding node property.
func Disabled(value any) Option {
	return propertyOption(func(props *Props) { props.Disabled = value })
}

// Value configures the corresponding node property.
func Value(value any) Option {
	return propertyOption(func(props *Props) { props.Value = value })
}

// Placeholder configures the corresponding node property.
func Placeholder(value string) Option {
	return propertyOption(func(props *Props) { props.Placeholder = value })
}

// Multiline configures the corresponding node property.
func Multiline(value bool) Option {
	return propertyOption(func(props *Props) { props.Multiline = value })
}

// AriaLabel configures the corresponding node property.
func AriaLabel(value any) Option {
	return propertyOption(func(props *Props) { props.AriaLabel = value })
}

// Selected configures the corresponding node property.
func Selected(value any) Option {
	return propertyOption(func(props *Props) { props.Selected = value })
}

// Group configures the corresponding node property.
func Group(value any) Option {
	return propertyOption(func(props *Props) { props.Group = value })
}

// FocusOnPointer configures the corresponding node property.
func FocusOnPointer(value any) Option {
	return propertyOption(func(props *Props) { props.FocusOnPointer = value })
}

// FocusableWhenDisabled configures the corresponding node property.
func FocusableWhenDisabled(value any) Option {
	return propertyOption(func(props *Props) { props.FocusableWhenDisabled = value })
}

// HitSlop configures the corresponding node property.
func HitSlop(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlop = value })
}

// HitSlopTop configures the corresponding node property.
func HitSlopTop(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopTop = value })
}

// HitSlopRight configures the corresponding node property.
func HitSlopRight(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopRight = value })
}

// HitSlopBottom configures the corresponding node property.
func HitSlopBottom(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopBottom = value })
}

// HitSlopLeft configures the corresponding node property.
func HitSlopLeft(value any) Option {
	return propertyOption(func(props *Props) { props.HitSlopLeft = value })
}

// Ref configures the corresponding node property.
func Ref(value func(*native.Node)) Option {
	return propertyOption(func(props *Props) { props.Ref = value })
}

// Password configures the corresponding node property.
func Password(value any) Option {
	return propertyOption(func(props *Props) { props.Password = value })
}

// Streaming configures the corresponding node property.
func Streaming(value any) Option {
	return propertyOption(func(props *Props) { props.Streaming = value })
}

// EstimatedItemHeight configures the corresponding node property.
func EstimatedItemHeight(value any) Option {
	return propertyOption(func(props *Props) { props.EstimatedItemHeight = value })
}

// Overscan configures the corresponding node property.
func Overscan(value any) Option {
	return propertyOption(func(props *Props) { props.Overscan = value })
}

// OverscanPixels configures the corresponding node property.
func OverscanPixels(value any) Option {
	return propertyOption(func(props *Props) { props.OverscanPixels = value })
}

// ItemHeights configures the corresponding node property.
func ItemHeights(value any) Option {
	return propertyOption(func(props *Props) { props.ItemHeights = value })
}

// ListAlignment configures the corresponding node property.
func ListAlignment(value string) Option {
	return propertyOption(func(props *Props) { props.ListAlignment = value })
}

// FollowMode configures the corresponding node property.
func FollowMode(value string) Option {
	return propertyOption(func(props *Props) { props.FollowMode = value })
}

// ShaderParameters configures the corresponding node property.
func ShaderParameters(value any) Option {
	return propertyOption(func(props *Props) { props.ShaderParameters = value })
}

// Invalid configures the corresponding node property.
func Invalid(value any) Option {
	return propertyOption(func(props *Props) { props.Invalid = value })
}

// Role configures the corresponding node property.
func Role(value any) Option {
	return propertyOption(func(props *Props) { props.Role = value })
}

// TabIndex configures the corresponding node property.
func TabIndex(value any) Option {
	return propertyOption(func(props *Props) { props.TabIndex = value })
}

// Overlay configures the corresponding node property.
func Overlay(value any) Option {
	return propertyOption(func(props *Props) { props.Overlay = value })
}

// FocusTrap configures the corresponding node property.
func FocusTrap(value any) Option {
	return propertyOption(func(props *Props) { props.FocusTrap = value })
}

// RestorePreviousFocus configures the corresponding node property.
func RestorePreviousFocus(value any) Option {
	return propertyOption(func(props *Props) { props.RestorePreviousFocus = value })
}

// AutoFocus configures the corresponding node property.
func AutoFocus(value any) Option {
	return propertyOption(func(props *Props) { props.AutoFocus = value })
}

// AriaModal configures the corresponding node property.
func AriaModal(value any) Option {
	return propertyOption(func(props *Props) { props.AriaModal = value })
}

// DismissOnEscape configures the corresponding node property.
func DismissOnEscape(value any) Option {
	return propertyOption(func(props *Props) { props.DismissOnEscape = value })
}

// DismissOnPointerOutside configures the corresponding node property.
func DismissOnPointerOutside(value any) Option {
	return propertyOption(func(props *Props) { props.DismissOnPointerOutside = value })
}

// TooltipText configures the corresponding node property.
func TooltipText(value any) Option {
	return propertyOption(func(props *Props) { props.TooltipText = value })
}

// TooltipPlacement configures the corresponding node property.
func TooltipPlacement(value any) Option {
	return propertyOption(func(props *Props) { props.TooltipPlacement = value })
}

// TooltipDelay configures the corresponding node property.
func TooltipDelay(value any) Option {
	return propertyOption(func(props *Props) { props.TooltipDelay = value })
}

// TooltipGap configures the corresponding node property.
func TooltipGap(value any) Option {
	return propertyOption(func(props *Props) { props.TooltipGap = value })
}

// TooltipViewportMargin configures the corresponding node property.
func TooltipViewportMargin(value any) Option {
	return propertyOption(func(props *Props) { props.TooltipViewportMargin = value })
}

// AnchorTarget configures the corresponding node property.
func AnchorTarget(value any) Option {
	return propertyOption(func(props *Props) { props.AnchorTarget = value })
}

// AnchorPlacement configures the corresponding node property.
func AnchorPlacement(value any) Option {
	return propertyOption(func(props *Props) { props.AnchorPlacement = value })
}

// AnchorGap configures the corresponding node property.
func AnchorGap(value any) Option {
	return propertyOption(func(props *Props) { props.AnchorGap = value })
}

// ViewportMargin configures the corresponding node property.
func ViewportMargin(value any) Option {
	return propertyOption(func(props *Props) { props.ViewportMargin = value })
}

// Keymap configures the corresponding node property.
func Keymap(value any) Option {
	return propertyOption(func(props *Props) { props.Keymap = value })
}

// Draggable configures the corresponding node property.
func Draggable(value any) Option {
	return propertyOption(func(props *Props) { props.Draggable = value })
}

// DropKinds configures the corresponding node property.
func DropKinds(value any) Option {
	return propertyOption(func(props *Props) { props.DropKinds = value })
}
