// Code generated by optionsgen; DO NOT EDIT.

package ui

// ObjectFit sets the corresponding style property.
func (style StyleBuilder) ObjectFit(value string) StyleBuilder {
	return style.configure(styleObjectFit(value))
}

// WordWrap sets the corresponding style property.
func (style StyleBuilder) WordWrap(value string) StyleBuilder {
	return style.configure(styleWordWrap(value))
}

// TransitionTimingFunction sets the corresponding style property.
func (style StyleBuilder) TransitionTimingFunction(value any) StyleBuilder {
	return style.configure(styleTransitionTimingFunction(value))
}

// PaddingInlineStart sets the corresponding style property.
func (style StyleBuilder) PaddingInlineStart(value any) StyleBuilder {
	return style.configure(stylePaddingInlineStart(value))
}

// PaddingInlineEnd sets the corresponding style property.
func (style StyleBuilder) PaddingInlineEnd(value any) StyleBuilder {
	return style.configure(stylePaddingInlineEnd(value))
}

// MarginInlineStart sets the corresponding style property.
func (style StyleBuilder) MarginInlineStart(value any) StyleBuilder {
	return style.configure(styleMarginInlineStart(value))
}

// MarginInlineEnd sets the corresponding style property.
func (style StyleBuilder) MarginInlineEnd(value any) StyleBuilder {
	return style.configure(styleMarginInlineEnd(value))
}

// BorderInlineStartWidth sets the corresponding style property.
func (style StyleBuilder) BorderInlineStartWidth(value any) StyleBuilder {
	return style.configure(styleBorderInlineStartWidth(value))
}

// BorderInlineEndWidth sets the corresponding style property.
func (style StyleBuilder) BorderInlineEndWidth(value any) StyleBuilder {
	return style.configure(styleBorderInlineEndWidth(value))
}

// AspectRatio sets the corresponding style property.
func (style StyleBuilder) AspectRatio(value any) StyleBuilder {
	return style.configure(styleAspectRatio(value))
}

// GridColumn sets the corresponding style property.
func (style StyleBuilder) GridColumn(value any) StyleBuilder {
	return style.configure(styleGridColumn(value))
}

// GridRow sets the corresponding style property.
func (style StyleBuilder) GridRow(value any) StyleBuilder {
	return style.configure(styleGridRow(value))
}

// BorderStartWidth sets the corresponding style property.
func (style StyleBuilder) BorderStartWidth(value any) StyleBuilder {
	return style.configure(styleBorderStartWidth(value))
}

// BorderEndWidth sets the corresponding style property.
func (style StyleBuilder) BorderEndWidth(value any) StyleBuilder {
	return style.configure(styleBorderEndWidth(value))
}

// Background sets the corresponding style property.
func (style StyleBuilder) Background(value any) StyleBuilder {
	return style.configure(styleBackground(value))
}

// BackgroundGradient sets the corresponding style property.
func (style StyleBuilder) BackgroundGradient(value any) StyleBuilder {
	return style.configure(styleBackgroundGradient(value))
}

// TransitionProperty sets the corresponding style property.
func (style StyleBuilder) TransitionProperty(value any) StyleBuilder {
	return style.configure(styleTransitionProperty(value))
}

// TransitionDuration sets the corresponding style property.
func (style StyleBuilder) TransitionDuration(value any) StyleBuilder {
	return style.configure(styleTransitionDuration(value))
}

// TransitionEasing sets the corresponding style property.
func (style StyleBuilder) TransitionEasing(value any) StyleBuilder {
	return style.configure(styleTransitionEasing(value))
}

// TransitionMaxFps sets the corresponding style property.
func (style StyleBuilder) TransitionMaxFps(value any) StyleBuilder {
	return style.configure(styleTransitionMaxFps(value))
}

// ScrollToEndRevision sets the corresponding style property.
func (style StyleBuilder) ScrollToEndRevision(value any) StyleBuilder {
	return style.configure(styleScrollToEndRevision(value))
}

// TextDecoration sets the corresponding style property.
func (style StyleBuilder) TextDecoration(value string) StyleBuilder {
	return style.configure(styleTextDecoration(value))
}

// InvalidStyle merges the Invalid interaction style.
func (style StyleBuilder) InvalidStyle(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleInvalidStyle(build(Style())))
}

// Dragging merges the Dragging interaction style.
func (style StyleBuilder) Dragging(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleDragging(build(Style())))
}

// DragOver merges the DragOver interaction style.
func (style StyleBuilder) DragOver(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleDragOver(build(Style())))
}

// FocusWithin merges the FocusWithin interaction style.
func (style StyleBuilder) FocusWithin(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleFocusWithin(build(Style())))
}

// GridTemplateColumns sets the corresponding style property.
func (style StyleBuilder) GridTemplateColumns(value any) StyleBuilder {
	return style.configure(styleGridTemplateColumns(value))
}

// GridTemplateRows sets the corresponding style property.
func (style StyleBuilder) GridTemplateRows(value any) StyleBuilder {
	return style.configure(styleGridTemplateRows(value))
}

// GridAutoFlow sets the corresponding style property.
func (style StyleBuilder) GridAutoFlow(value string) StyleBuilder {
	return style.configure(styleGridAutoFlow(value))
}

// GridColumnStart sets the corresponding style property.
func (style StyleBuilder) GridColumnStart(value any) StyleBuilder {
	return style.configure(styleGridColumnStart(value))
}

// GridColumnEnd sets the corresponding style property.
func (style StyleBuilder) GridColumnEnd(value any) StyleBuilder {
	return style.configure(styleGridColumnEnd(value))
}

// GridColumnSpan sets the corresponding style property.
func (style StyleBuilder) GridColumnSpan(value any) StyleBuilder {
	return style.configure(styleGridColumnSpan(value))
}

// GridRowStart sets the corresponding style property.
func (style StyleBuilder) GridRowStart(value any) StyleBuilder {
	return style.configure(styleGridRowStart(value))
}

// GridRowEnd sets the corresponding style property.
func (style StyleBuilder) GridRowEnd(value any) StyleBuilder {
	return style.configure(styleGridRowEnd(value))
}

// GridRowSpan sets the corresponding style property.
func (style StyleBuilder) GridRowSpan(value any) StyleBuilder {
	return style.configure(styleGridRowSpan(value))
}

// PaddingStart sets the corresponding style property.
func (style StyleBuilder) PaddingStart(value any) StyleBuilder {
	return style.configure(stylePaddingStart(value))
}

// PaddingEnd sets the corresponding style property.
func (style StyleBuilder) PaddingEnd(value any) StyleBuilder {
	return style.configure(stylePaddingEnd(value))
}

// MarginStart sets the corresponding style property.
func (style StyleBuilder) MarginStart(value any) StyleBuilder {
	return style.configure(styleMarginStart(value))
}

// MarginEnd sets the corresponding style property.
func (style StyleBuilder) MarginEnd(value any) StyleBuilder {
	return style.configure(styleMarginEnd(value))
}

// BorderTopWidth sets the corresponding style property.
func (style StyleBuilder) BorderTopWidth(value any) StyleBuilder {
	return style.configure(styleBorderTopWidth(value))
}

// BorderRightWidth sets the corresponding style property.
func (style StyleBuilder) BorderRightWidth(value any) StyleBuilder {
	return style.configure(styleBorderRightWidth(value))
}

// BorderBottomWidth sets the corresponding style property.
func (style StyleBuilder) BorderBottomWidth(value any) StyleBuilder {
	return style.configure(styleBorderBottomWidth(value))
}

// BorderLeftWidth sets the corresponding style property.
func (style StyleBuilder) BorderLeftWidth(value any) StyleBuilder {
	return style.configure(styleBorderLeftWidth(value))
}

// BorderTopLeftRadius sets the corresponding style property.
func (style StyleBuilder) BorderTopLeftRadius(value any) StyleBuilder {
	return style.configure(styleBorderTopLeftRadius(value))
}

// BorderTopRightRadius sets the corresponding style property.
func (style StyleBuilder) BorderTopRightRadius(value any) StyleBuilder {
	return style.configure(styleBorderTopRightRadius(value))
}

// BorderBottomLeftRadius sets the corresponding style property.
func (style StyleBuilder) BorderBottomLeftRadius(value any) StyleBuilder {
	return style.configure(styleBorderBottomLeftRadius(value))
}

// BorderBottomRightRadius sets the corresponding style property.
func (style StyleBuilder) BorderBottomRightRadius(value any) StyleBuilder {
	return style.configure(styleBorderBottomRightRadius(value))
}

// BorderStyle sets the corresponding style property.
func (style StyleBuilder) BorderStyle(value string) StyleBuilder {
	return style.configure(styleBorderStyle(value))
}

// BoxShadow sets the corresponding style property.
func (style StyleBuilder) BoxShadow(value any) StyleBuilder {
	return style.configure(styleBoxShadow(value))
}

// TextShadow sets the corresponding style property.
func (style StyleBuilder) TextShadow(value any) StyleBuilder {
	return style.configure(styleTextShadow(value))
}

// TextDecorationLine sets the corresponding style property.
func (style StyleBuilder) TextDecorationLine(value string) StyleBuilder {
	return style.configure(styleTextDecorationLine(value))
}

// TextDecorationColor sets the corresponding style property.
func (style StyleBuilder) TextDecorationColor(value any) StyleBuilder {
	return style.configure(styleTextDecorationColor(value))
}

// TextDecorationStyle sets the corresponding style property.
func (style StyleBuilder) TextDecorationStyle(value string) StyleBuilder {
	return style.configure(styleTextDecorationStyle(value))
}

// TextDecorationThickness sets the corresponding style property.
func (style StyleBuilder) TextDecorationThickness(value any) StyleBuilder {
	return style.configure(styleTextDecorationThickness(value))
}

// WordSpacing sets the corresponding style property.
func (style StyleBuilder) WordSpacing(value any) StyleBuilder {
	return style.configure(styleWordSpacing(value))
}

// WordBreak sets the corresponding style property.
func (style StyleBuilder) WordBreak(value string) StyleBuilder {
	return style.configure(styleWordBreak(value))
}

// OverflowWrap sets the corresponding style property.
func (style StyleBuilder) OverflowWrap(value string) StyleBuilder {
	return style.configure(styleOverflowWrap(value))
}

// Hyphens sets the corresponding style property.
func (style StyleBuilder) Hyphens(value string) StyleBuilder {
	return style.configure(styleHyphens(value))
}

// TextDirection sets the corresponding style property.
func (style StyleBuilder) TextDirection(value string) StyleBuilder {
	return style.configure(styleTextDirection(value))
}

// Direction sets the corresponding style property.
func (style StyleBuilder) Direction(value string) StyleBuilder {
	return style.configure(styleDirection(value))
}

// BackgroundImage sets the corresponding style property.
func (style StyleBuilder) BackgroundImage(value string) StyleBuilder {
	return style.configure(styleBackgroundImage(value))
}

// BackgroundSize sets the corresponding style property.
func (style StyleBuilder) BackgroundSize(value string) StyleBuilder {
	return style.configure(styleBackgroundSize(value))
}

// BackgroundRepeat sets the corresponding style property.
func (style StyleBuilder) BackgroundRepeat(value string) StyleBuilder {
	return style.configure(styleBackgroundRepeat(value))
}

// BackgroundPosition sets the corresponding style property.
func (style StyleBuilder) BackgroundPosition(value string) StyleBuilder {
	return style.configure(styleBackgroundPosition(value))
}

// Filter sets the corresponding style property.
func (style StyleBuilder) Filter(value any) StyleBuilder {
	return style.configure(styleFilter(value))
}

// BackdropFilter sets the corresponding style property.
func (style StyleBuilder) BackdropFilter(value any) StyleBuilder {
	return style.configure(styleBackdropFilter(value))
}

// MixBlendMode sets the corresponding style property.
func (style StyleBuilder) MixBlendMode(value string) StyleBuilder {
	return style.configure(styleMixBlendMode(value))
}

// Transition sets the corresponding style property.
func (style StyleBuilder) Transition(value any) StyleBuilder {
	return style.configure(styleTransition(value))
}

// ScrollSnapType sets the corresponding style property.
func (style StyleBuilder) ScrollSnapType(value string) StyleBuilder {
	return style.configure(styleScrollSnapType(value))
}

// ScrollSnapX sets the corresponding style property.
func (style StyleBuilder) ScrollSnapX(value string) StyleBuilder {
	return style.configure(styleScrollSnapX(value))
}

// ScrollSnapY sets the corresponding style property.
func (style StyleBuilder) ScrollSnapY(value string) StyleBuilder {
	return style.configure(styleScrollSnapY(value))
}

// ScrollSnapAlign sets the corresponding style property.
func (style StyleBuilder) ScrollSnapAlign(value string) StyleBuilder {
	return style.configure(styleScrollSnapAlign(value))
}

// ScrollSnapStop sets the corresponding style property.
func (style StyleBuilder) ScrollSnapStop(value string) StyleBuilder {
	return style.configure(styleScrollSnapStop(value))
}

// Display sets the corresponding style property.
func (style StyleBuilder) Display(value string) StyleBuilder {
	return style.configure(styleDisplay(value))
}

// FlexDirection sets the corresponding style property.
func (style StyleBuilder) FlexDirection(value string) StyleBuilder {
	return style.configure(styleFlexDirection(value))
}

// FlexGrow sets the corresponding style property.
func (style StyleBuilder) FlexGrow(value any) StyleBuilder {
	return style.configure(styleFlexGrow(value))
}

// FlexShrink sets the corresponding style property.
func (style StyleBuilder) FlexShrink(value any) StyleBuilder {
	return style.configure(styleFlexShrink(value))
}

// FlexBasis sets the corresponding style property.
func (style StyleBuilder) FlexBasis(value any) StyleBuilder {
	return style.configure(styleFlexBasis(value))
}

// AlignItems sets the corresponding style property.
func (style StyleBuilder) AlignItems(value string) StyleBuilder {
	return style.configure(styleAlignItems(value))
}

// AlignSelf sets the corresponding style property.
func (style StyleBuilder) AlignSelf(value string) StyleBuilder {
	return style.configure(styleAlignSelf(value))
}

// JustifyContent sets the corresponding style property.
func (style StyleBuilder) JustifyContent(value string) StyleBuilder {
	return style.configure(styleJustifyContent(value))
}

// AlignContent sets the corresponding style property.
func (style StyleBuilder) AlignContent(value string) StyleBuilder {
	return style.configure(styleAlignContent(value))
}

// Gap sets the corresponding style property.
func (style StyleBuilder) Gap(value any) StyleBuilder {
	return style.configure(styleGap(value))
}

// ColumnGap sets the corresponding style property.
func (style StyleBuilder) ColumnGap(value any) StyleBuilder {
	return style.configure(styleColumnGap(value))
}

// RowGap sets the corresponding style property.
func (style StyleBuilder) RowGap(value any) StyleBuilder {
	return style.configure(styleRowGap(value))
}

// Width sets the corresponding style property.
func (style StyleBuilder) Width(value any) StyleBuilder {
	return style.configure(styleWidth(value))
}

// Height sets the corresponding style property.
func (style StyleBuilder) Height(value any) StyleBuilder {
	return style.configure(styleHeight(value))
}

// MinWidth sets the corresponding style property.
func (style StyleBuilder) MinWidth(value any) StyleBuilder {
	return style.configure(styleMinWidth(value))
}

// MinHeight sets the corresponding style property.
func (style StyleBuilder) MinHeight(value any) StyleBuilder {
	return style.configure(styleMinHeight(value))
}

// MaxWidth sets the corresponding style property.
func (style StyleBuilder) MaxWidth(value any) StyleBuilder {
	return style.configure(styleMaxWidth(value))
}

// MaxHeight sets the corresponding style property.
func (style StyleBuilder) MaxHeight(value any) StyleBuilder {
	return style.configure(styleMaxHeight(value))
}

// Padding sets the corresponding style property.
func (style StyleBuilder) Padding(value any) StyleBuilder {
	return style.configure(stylePadding(value))
}

// PaddingTop sets the corresponding style property.
func (style StyleBuilder) PaddingTop(value any) StyleBuilder {
	return style.configure(stylePaddingTop(value))
}

// PaddingRight sets the corresponding style property.
func (style StyleBuilder) PaddingRight(value any) StyleBuilder {
	return style.configure(stylePaddingRight(value))
}

// PaddingBottom sets the corresponding style property.
func (style StyleBuilder) PaddingBottom(value any) StyleBuilder {
	return style.configure(stylePaddingBottom(value))
}

// PaddingLeft sets the corresponding style property.
func (style StyleBuilder) PaddingLeft(value any) StyleBuilder {
	return style.configure(stylePaddingLeft(value))
}

// Margin sets the corresponding style property.
func (style StyleBuilder) Margin(value any) StyleBuilder {
	return style.configure(styleMargin(value))
}

// MarginTop sets the corresponding style property.
func (style StyleBuilder) MarginTop(value any) StyleBuilder {
	return style.configure(styleMarginTop(value))
}

// MarginRight sets the corresponding style property.
func (style StyleBuilder) MarginRight(value any) StyleBuilder {
	return style.configure(styleMarginRight(value))
}

// MarginBottom sets the corresponding style property.
func (style StyleBuilder) MarginBottom(value any) StyleBuilder {
	return style.configure(styleMarginBottom(value))
}

// MarginLeft sets the corresponding style property.
func (style StyleBuilder) MarginLeft(value any) StyleBuilder {
	return style.configure(styleMarginLeft(value))
}

// BackgroundColor sets the corresponding style property.
func (style StyleBuilder) BackgroundColor(value any) StyleBuilder {
	return style.configure(styleBackgroundColor(value))
}

// TextColor sets the corresponding style property.
func (style StyleBuilder) TextColor(value any) StyleBuilder {
	return style.configure(styleTextColor(value))
}

// Opacity sets the corresponding style property.
func (style StyleBuilder) Opacity(value any) StyleBuilder {
	return style.configure(styleOpacity(value))
}

// BorderWidth sets the corresponding style property.
func (style StyleBuilder) BorderWidth(value any) StyleBuilder {
	return style.configure(styleBorderWidth(value))
}

// BorderColor sets the corresponding style property.
func (style StyleBuilder) BorderColor(value any) StyleBuilder {
	return style.configure(styleBorderColor(value))
}

// BorderRadius sets the corresponding style property.
func (style StyleBuilder) BorderRadius(value any) StyleBuilder {
	return style.configure(styleBorderRadius(value))
}

// FontSize sets the corresponding style property.
func (style StyleBuilder) FontSize(value any) StyleBuilder {
	return style.configure(styleFontSize(value))
}

// FontFamily sets the corresponding style property.
func (style StyleBuilder) FontFamily(value string) StyleBuilder {
	return style.configure(styleFontFamily(value))
}

// FontWeight sets the corresponding style property.
func (style StyleBuilder) FontWeight(value any) StyleBuilder {
	return style.configure(styleFontWeight(value))
}

// LineHeight sets the corresponding style property.
func (style StyleBuilder) LineHeight(value any) StyleBuilder {
	return style.configure(styleLineHeight(value))
}

// TextAlign sets the corresponding style property.
func (style StyleBuilder) TextAlign(value string) StyleBuilder {
	return style.configure(styleTextAlign(value))
}

// Cursor sets the corresponding style property.
func (style StyleBuilder) Cursor(value string) StyleBuilder {
	return style.configure(styleCursor(value))
}

// AppRegion sets the corresponding style property.
func (style StyleBuilder) AppRegion(value string) StyleBuilder {
	return style.configure(styleAppRegion(value))
}

// UserSelect sets the corresponding style property.
func (style StyleBuilder) UserSelect(value string) StyleBuilder {
	return style.configure(styleUserSelect(value))
}

// Position sets the corresponding style property.
func (style StyleBuilder) Position(value string) StyleBuilder {
	return style.configure(stylePosition(value))
}

// Overflow sets the corresponding style property.
func (style StyleBuilder) Overflow(value string) StyleBuilder {
	return style.configure(styleOverflow(value))
}

// OverflowX sets the corresponding style property.
func (style StyleBuilder) OverflowX(value string) StyleBuilder {
	return style.configure(styleOverflowX(value))
}

// OverflowY sets the corresponding style property.
func (style StyleBuilder) OverflowY(value string) StyleBuilder {
	return style.configure(styleOverflowY(value))
}

// Visibility sets the corresponding style property.
func (style StyleBuilder) Visibility(value string) StyleBuilder {
	return style.configure(styleVisibility(value))
}

// LetterSpacing sets the corresponding style property.
func (style StyleBuilder) LetterSpacing(value any) StyleBuilder {
	return style.configure(styleLetterSpacing(value))
}

// TextTransform sets the corresponding style property.
func (style StyleBuilder) TextTransform(value string) StyleBuilder {
	return style.configure(styleTextTransform(value))
}

// LineClamp sets the corresponding style property.
func (style StyleBuilder) LineClamp(value any) StyleBuilder {
	return style.configure(styleLineClamp(value))
}

// WhiteSpace sets the corresponding style property.
func (style StyleBuilder) WhiteSpace(value string) StyleBuilder {
	return style.configure(styleWhiteSpace(value))
}

// TextOverflow sets the corresponding style property.
func (style StyleBuilder) TextOverflow(value string) StyleBuilder {
	return style.configure(styleTextOverflow(value))
}

// Top sets the corresponding style property.
func (style StyleBuilder) Top(value any) StyleBuilder {
	return style.configure(styleTop(value))
}

// Right sets the corresponding style property.
func (style StyleBuilder) Right(value any) StyleBuilder {
	return style.configure(styleRight(value))
}

// Bottom sets the corresponding style property.
func (style StyleBuilder) Bottom(value any) StyleBuilder {
	return style.configure(styleBottom(value))
}

// Left sets the corresponding style property.
func (style StyleBuilder) Left(value any) StyleBuilder {
	return style.configure(styleLeft(value))
}

// Outline sets the corresponding style property.
func (style StyleBuilder) Outline(value any) StyleBuilder {
	return style.configure(styleOutline(value))
}

// OutlineWidth sets the corresponding style property.
func (style StyleBuilder) OutlineWidth(value any) StyleBuilder {
	return style.configure(styleOutlineWidth(value))
}

// OutlineColor sets the corresponding style property.
func (style StyleBuilder) OutlineColor(value any) StyleBuilder {
	return style.configure(styleOutlineColor(value))
}

// OutlineOffset sets the corresponding style property.
func (style StyleBuilder) OutlineOffset(value any) StyleBuilder {
	return style.configure(styleOutlineOffset(value))
}

// OutlineStyle sets the corresponding style property.
func (style StyleBuilder) OutlineStyle(value string) StyleBuilder {
	return style.configure(styleOutlineStyle(value))
}

// Transform sets the corresponding style property.
func (style StyleBuilder) Transform(value any) StyleBuilder {
	return style.configure(styleTransform(value))
}

// TransformOrigin sets the corresponding style property.
func (style StyleBuilder) TransformOrigin(value string) StyleBuilder {
	return style.configure(styleTransformOrigin(value))
}

// Hover merges the Hover interaction style.
func (style StyleBuilder) Hover(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleHover(build(Style())))
}

// Active merges the Active interaction style.
func (style StyleBuilder) Active(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleActive(build(Style())))
}

// FocusStyle merges the Focus interaction style.
func (style StyleBuilder) FocusStyle(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleFocus(build(Style())))
}

// DisabledStyle merges the Disabled interaction style.
func (style StyleBuilder) DisabledStyle(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleDisabledStyle(build(Style())))
}

// SelectedStyle merges the Selected interaction style.
func (style StyleBuilder) SelectedStyle(build func(StyleBuilder) StyleBuilder) StyleBuilder {
	return style.configure(styleSelectedStyle(build(Style())))
}
