#!/usr/bin/env bun
/** The Rust decoder remains the source of truth for every TypeScript wire ID and bound. */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const host = readFileSync(resolve(root, "crates/quickgui-host/src/lib.rs"), "utf8");
const tree = readFileSync(resolve(root, "crates/quickgui-host/src/tree.rs"), "utf8");
const version = /const PROTOCOL_VERSION: u16 = (\d+);/.exec(host)?.[1];
const properties = [...host.matchAll(/pub const ([A-Z_0-9]+): u16 = (\d+);/g)];
const tags = [...tree.matchAll(/(\d+) => Ok\(Self::([A-Za-z]+)\),/g)];
if (!version || properties.length < 100 || tags.length < 10)
  throw new Error("Rust protocol missing");
const camel = (name: string) =>
  name.toLowerCase().replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const pascal = (name: string) =>
  name
    .toLowerCase()
    .split("_")
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("")
    .replaceAll("SwiftUi", "SwiftUI")
    .replaceAll("QuickGui", "QuickGUI");
const limits = ["MAX_BATCH_BYTES", "MAX_MUTATIONS", "MAX_NODES", "MAX_STRING_BYTES", "MAX_EXTENSION_PROPS_BYTES"].map((name) => {
  const expression = new RegExp(`const ${name}: usize = ([0-9_ *]+);`).exec(host)?.[1];
  if (!expression) throw new Error(`Missing ${name}`);
  const value = expression
    .split("*")
    .reduce((n, part) => n * Number(part.replaceAll("_", "").trim()), 1);
  return `export const ${name} = ${value};`;
});
const source = [
  "// Generated by bun scripts/generate-typescript.ts. Do not edit.",
  `export const PROTOCOL_VERSION = ${version};`,
  ...limits,
  "export enum PropertyCode {",
  ...properties.map(([, name, id]) => `  ${pascal(name!)} = ${id},`),
  "}",
  "export enum NativeNodeTag {",
  ...tags.map(
    ([, id, name]) =>
      `  ${name!.replaceAll("SwiftUi", "SwiftUI").replaceAll("QuickGui", "QuickGUI")} = ${id},`,
  ),
  "}",
  "export const properties = {",
  ...properties.map(([, name, id]) => `  ${name === "COLOR" ? "textColor" : camel(name!)}: ${id},`),
  "} as const;",
  "export const tags = {",
  ...tags.map(([, id, name]) => `  ${name![0]!.toLowerCase() + name!.slice(1)}: ${id},`),
  "} as const;",
  "",
].join("\n");
const path = resolve(root, "packages/native/src/protocol.generated.ts");
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== source)
    throw new Error("Run bun scripts/generate-typescript.ts");
} else writeFileSync(path, source);
